jupyter/nbgrader

nbgrader/apps/assignapp.py

Currently it doesn't show up in the help.

Add lock cells preprocessor to assign app help

---

nbextensions/nbgrader.css
nbextensions/nbgrader.js

Handles a few edge cases where the total points weren't being properly hidden or updated.

Add/remove total points when toolbar is shown/hidden

---

nbextensions/nbgrader.js
nbgrader/apps/assignapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/checkgradeids.py

Tries to check for duplicate ids both in the nbextension and in `nbgrader assign`. Fixes #54

Verify cell ids

---

nbgrader/utils.py

Make sure we're updating the hash with bytes in python 3

Fix python 3 bug

---

nbgrader/html/formgrade.py

Currently they are sorted arbitrarily (sometimes by `_id`, sometimes by `student_id`).

Sort students by last name in the formgrader

---

nbgrader/api.py
nbgrader/preprocessors/overwritegradecells.py
nbgrader/preprocessors/savegradecells.py
nbgrader/utils.py

Save cell types in database

---

nbgrader/html/static/css/formgrade.css
nbgrader/html/static/js/formgrade.js

Save currently selected element when page is changed

---

nbgrader/html/static/css/formgrade.css
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl

Fixes #82 and changes the formgrader to look like this:
@smeylan is this what you were thinking of?

Add buttons for full and no credit

---

nbgrader/apps/formgradeapp.py
nbgrader/html/formgrade.py

Fix ip address for live notebook

---

nbextensions/nbgrader.js
nbgrader/preprocessors/checkgradeids.py
nbgrader/preprocessors/findstudentid.py
nbgrader/tests/base.py
nbgrader/tests/files/blank-grade-id.ipynb
nbgrader/tests/files/blank-points.ipynb
nbgrader/tests/files/duplicate-grade-ids.ipynb
nbgrader/tests/files/test-v3.ipynb
nbgrader/tests/files/test.ipynb
nbgrader/tests/test_checkgradeids.py
nbgrader/tests/test_computechecksums.py
nbgrader/tests/test_findstudentid.py

This adds tests for `CheckGradeIds`, `ComputeChecksums`, and `FindStudentID`.
Edit: this will also fix #64

Add tests for some of the preprocessors

---

.travis.yml

Let see if this fix the docs building.

Clone ipython master in home and not subdir

---

nbgrader/preprocessors/overwritecells.py

Performs a valid conversion between cell types -- more is required than just setting the `cell_type` attribute.

Fix bugs in overwriting the cell type

---

nbgrader/html/templates/student_submissions.tpl

Fix path to submission from student view

---

nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/tests/test_api.py
nbgrader/tests/test_gradebook.py

This turns most of the `@property` methods in the declarative mapping into actual queryable columns. This adds a slight speed improvement. On top of that, this also moves all the methods for calculating average scores into the gradebook, which then uses proper joins and stuff for massive speed improvements. Additionally, I added a few helper functions for querying information about all the students or submissions at once, which dramatically speeds up load times in the formgrader.

Optimize SQL queries

---

nbgrader/apps/submitapp.py

Make the timestamp's timezone configurable

---

.travis.yml
README.md
scripts/runtests

Add coverage to tests

---

nbgrader/apps/formgradeapp.py
nbgrader/html/formgrade.py
nbgrader/html/templates/formgrade.tpl

@jhamrick @ellisonbg 
closes #145

Make launching single notebook server optional.

---

.travis.yml

Hopefully will result in faster travis builds.

Use sudo=false for travis builds

---

.travis.yml
nbgrader/apps/formgradeapp.py
nbgrader/auth/__init__.py
nbgrader/auth/base.py
nbgrader/auth/hubauth.py
nbgrader/auth/noauth.py
nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/assignment_notebooks.tpl
nbgrader/html/templates/assignments.tpl
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/gradebook.tpl
nbgrader/html/templates/notebook_submissions.tpl
nbgrader/html/templates/student_assignments.tpl
nbgrader/html/templates/student_submissions.tpl
nbgrader/html/templates/students.tpl
nbgrader/tests/base.py
nbgrader/tests/fakeuser.py
nbgrader/tests/test_nbgrader_formgrade.py
nbgrader/tests/test_nbgrader_formgrade_hubauth.py
setup.py

Hey @jhamrick ,
Here's a simple extensible authentication scheme.  
FormgradeApp.authenticator_class can be used to change the authenticator.  `BaseAuth` is the base authenticator class.  A `NoAuth` class is provided as the default, and retains current behavior of `formgrade`.  I moved the `start_nbserver` traitlet and nbserver launching logic into `NoAuth`.
The `HubAuth`, empty now, will contain the logic for authenticating with JupyterHub.
Let me know what you think of this design.  I've tested it locally and everything seems to work as-is.  The not yet implement `HubAuth` can be tested quickly (when it's done) using `nbgrader formgrade --FormgradeApp.authenticator_class='nbgrader.auth.hubauth.HubAuth'`.
closes #145

WIP: nbgrader authentication

---

nbgrader/install.py
nbgrader/tests/test_nbextension.py

Or you would just deactivate all extension, which much likely not what
you want to do :-)
---- 
I think that make sens. (haven't tried though) 
Can comme up with a test also.

Actually prune if empty dict, not other way around.

---

nbgrader/auth/hubauth.py

@jhamrick 
This is required for complex deployments.
I have an SSL terminating nginx sitting in front of the Hub and nbgrader.  I need to direct clients to nginx's HTTPS domain.

Make the hub_base_url configurable.

---

.travis.yml
requirements.txt

Pin to version 3.x in travis

---

nbgrader/apps/feedbackapp.py

Include CSS header in feedback

---

nbgrader/apps/baseapp.py

Process submissions in sorted order

---

nbgrader/apps/baseapp.py

This modifies the apps that inherit from `BaseNbConvertApp` to process assignments atomically, such that if there is an error during processing, nbgrader will clean up the failed destination files.
Fixes #216

Atomically process assignments

---

nbgrader/install.py
nbgrader/tests/test_nbextension.py

Better nbextension installation defaults

---

nbgrader/api.py
nbgrader/tests/test_api.py

Correct the student max score

---

nbgrader/html/formgrade.py

Handle no lastname and duedate in formgrader.

---

nbgrader/html/formgrade.py

Fixing small issues with get logic in formgrader.

---

nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl
nbgrader/tests/test_nbgrader_formgrade.py

Only compute next/previous submissions on demand

---

nbgrader/apps/baseapp.py
nbgrader/config.py

Adds syntax highlighting to nbgrader

added syntax highlighting of logs using tornado

---

nbgrader/tests/apps/files/side-effects.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py

Add test to check for autograding side effects

---

.coveragerc
nbgrader/api.py
nbgrader/apps/listapp.py
nbgrader/auth/noauth.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/utils.py

* Fixes #214
* Fixes #213 
* Fixes #212 
* Fixes #211

Add missing tests for new apps

---

nbgrader/api.py
nbgrader/tests/api/test_gradebook.py

This adds some convenience methods for deleting submissions/students/assignments.

Add api methods to delete submissions, students, and assignments

---

nbgrader/html/templates/formgrade.tpl
nbgrader/tests/formgrader/test_formgrader.py

Fix next/prev navigation in formgrader

---

nbgrader/apps/baseapp.py

Fix path to rmtree

---

nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl

Make the save glyphicon less confusing

---

nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/formgrade_404.tpl
nbgrader/html/templates/formgrade_macros.tpl

Fixes #260
This won't actually skip over notebooks, but it will give a more useful error page, and preserve keyboard shortcuts (so you can still do things like move to the next submissions).

Missing assignment

---

nbgrader/apps/autogradeapp.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Skip extra nbs

---

.travis.yml
nbgrader/apps/formgradeapp.py
nbgrader/html/formgrade.py
nbgrader/html/templates/formgrade.tpl

Allow local installation of mathjax

---

nbgrader/apps/listapp.py
nbgrader/tests/apps/test_nbgrader_list.py

Fix nbgrader list

---

nbgrader/nbextensions/nbgrader/create_assignment.js
nbgrader/tests/nbextensions/test_nbextension.py

Fix update total points in notebook extension

---

nbgrader/apps/nbgraderapp.py
nbgrader/preprocessors/base.py
nbgrader/preprocessors/clearsolutions.py
nbgrader/preprocessors/displayautogrades.py

Document config options

---

nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/html/templates/student_assignments.tpl
nbgrader/tests/api/test_gradebook.py

List students who haven't submitted anything

---

nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/tests/formgrader/test_formgrader.py

Fixes #121
If it is a written answer (i.e. has a score and a comment field), this will cause the score to be preferentially focused when navigating between assignments.

Focus on score when navigating to next/previous assignment

---

nbgrader/apps/assignapp.py
nbgrader/apps/baseapp.py
nbgrader/config.py
nbgrader/tests/apps/base.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_feedback.py

Make nbconvert-based apps use read-only permissions

---

nbgrader/api.py
nbgrader/html/templates/assignment_notebooks.tpl
nbgrader/html/templates/student_assignments.tpl
nbgrader/tests/api/test_models.py

Add column for needs manual grade

---

nbgrader/tests/formgrader/base.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/nbextensions/test_nbextension.py

Hopefully this will decrease the number of test failures...

Increase webdriver timeouts

---

.coveragerc
.travis.yml
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/formgrader/test_gradebook_navigation.py
nbgrader/tests/nbextensions/test_nbextension.py
tasks.py

They fail frequently, and it's annoying to have to rerun all the tests again when it's just the javascript stuff.

Run js tests in a different build

---

.coveragerc
.travis.yml
nbgrader/__main__.py
nbgrader/api.py
nbgrader/apps/nbgraderapp.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/test_nbgrader.py
tasks.py

Removing old, unused files, adding some missing test cases, etc.

Miscellaneous coverage cleanup

---

.travis.yml
nbgrader/tests/formgrader/test_gradebook_navigation.py
requirements.txt
tasks.py

Until I figure out what's going on with jupyter/jupyterhub#262, this marks the relevant failing tests as xfail so I can continue to work on other stuff.

Fix ipython version and mark xfailing tests

---

nbgrader/nbextensions/nbgrader/create_assignment.js
nbgrader/preprocessors/checkcellmetadata.py
nbgrader/tests/nbextensions/test_nbextension.py
nbgrader/tests/preprocessors/test_checkcellmetadata.py

As per a discussion with Brian, this changes the notebook extension so that cell ids are only validated on save, rather than as soon as they are modified. It also adds in better validation in the `CheckCellMetadata` preprocessor.

Validation of cell ids

---

nbgrader/tests/formgrader/test_gradebook_navigation.py

Remove xfailing tests

---

nbgrader/tests/formgrader/test_formgrader_js.py

I don't know why these weren't failing when I made the PR that added these, or why they didn't fail when the PR was merged into master... chance, I guess?

Fix formgrader js tests

---

nbgrader/apps/autogradeapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/deduplicateids.py
nbgrader/tests/preprocessors/test_deduplicateids.py

Add deduplicate ids preprocessor

---

nbgrader/preprocessors/displayautogrades.py
nbgrader/tests/preprocessors/test_displayautogrades.py

Test DisplayAutoGrades preprocessor

---

nbgrader/auth/hubauth.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

Fix JupyterHub login url redirect

---

nbgrader/preprocessors/overwritecells.py

fixes warning about points

---

nbgrader/html/templates/feedback.tpl

Adds markdown formatting to instructor feedback comments.

implements #254

---

nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/files/source
nbgrader/tests/formgrader/files/submitted

Working on #321, Travis, please test.

try to get rid of filenames

---

CONTRIBUTING.md
README.md

Edited to make dev install process instructions clearer.

fixes #318 and #322

---

tasks.py

Install released version of jupyterhub

---

docs/source/user_guide/02_developing_assignments.rst

Added documentation for writing test cases.

add test docs

---

docs/source/user_guide/03_generating_assignments.ipynb

I've added some detail, edited the prose, and provided some user-friendly format enhancements. Please suggest changes as desired.
This PR relates to Issue #283. 
When I made the changes, I thought ``nbgrader assign`` was part of the issue list. I'm happy to go back and do the others in the issue. I just wanted to get some feedback before I make too many changes :smile:

Add clarity to workflow example doc for generating assignments

---

tools/backport_pr.py
tools/contributer_list.py
tools/gh_api.py

Based on the one from the IPython repo.

Add backport-pr script

---

.travis.yml
README.md
flit.ini
tasks.py

I just tried, and it seem to work [for me](https://codecov.io/github/Carreau/nbgrader?ref=master). If you get annoyed by coverall, it seems easy to switch.

try codecov

---

nbgrader/apps/formgradeapp.py
nbgrader/auth/hubauth.py
nbgrader/html/formgrade.py
nbgrader/html/templates/gradebook_403.tpl
nbgrader/html/templates/gradebook_500.tpl
nbgrader/tests/formgrader/bad_manager.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/formgrader/test_auth_failures.py
nbgrader/tests/formgrader/test_configproxy_auth_failure.py

This checks for the various failure modes of using the formgrader with JupyterHub and adds nicer error pages for the cases in which those errors happen.

More informative error pages

---

nbgrader/auth/hubauth.py

This adds a specific ip address that the configurable-http-proxy should be able to proxy to. This is needed if the formgrader is running inside a container, because it might bind to for example `0.0.0.0` but the proxy should forward requests to the actual ip address of the machine or container.

Make it possible to connect to containerized formgrader

---

nbgrader/apps/listapp.py
nbgrader/apps/validateapp.py
nbgrader/preprocessors/displayautogrades.py
nbgrader/tests/apps/base.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/tests/preprocessors/files/submitted-changed.ipynb
nbgrader/tests/preprocessors/files/submitted-grade-cell-changed.ipynb
nbgrader/tests/preprocessors/files/submitted-locked-cell-changed.ipynb
nbgrader/tests/preprocessors/files/submitted-unchanged.ipynb
nbgrader/tests/preprocessors/test_displayautogrades.py

This is a prerequisite for #357. I'm going to try to split that PR up into a few different pieces to make testing and review easier.

Add --json flags to nbgrader list and nbgrader validate

---

.travis.yml
tasks.py

Switch to travis container builds

---

nbgrader/__init__.py
nbgrader/_version.py
nbgrader/apps/nbgraderapp.py

Print out python version in addition to nbgrader version

---

nbgrader/apps/baseapp.py

Change default cache location

---

docs/source/build_docs.py
nbgrader/apps/baseapp.py
nbgrader/apps/nbgraderapp.py

Generate RST config options

---

nbgrader/apps/extensionapp.py

Use jupyter extension app functionality

---

nbgrader/tests/formgrader/base.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/test_auth_failures.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/formgrader/test_gradebook_navigation.py
nbgrader/tests/nbextensions/conftest.py
tasks.py

Trying to debug further some of the travis timeouts :-(

Set phantomjs timeouts

---

nbgrader/api.py

Postgres wants the groupby to include anything that is queried that isn't also aggregated.

Fix the subqueries so that they work with postgres

---

docs/source/build_docs.py
flit.ini
nbgrader/__main__.py
nbgrader/auth/hubauth.py
nbgrader/auth/noauth.py
nbgrader/nbextensions/assignment_list/handlers.py
nbgrader/tests/__init__.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/formgrader/test_nbgrader_formgrade.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py
setup.py

Use sys.executable to run suprocesses

---

docs/source/build_docs.py
docs/source/user_guide/01_philosophy.rst
docs/source/user_guide/03_generating_assignments.ipynb
docs/source/user_guide/04_autograding.ipynb
docs/source/user_guide/05_manual_grading.rst
docs/source/user_guide/06_returning_feedback.ipynb
docs/source/user_guide/07_releasing_assignments.ipynb
docs/source/user_guide/08_fetching_assignments.ipynb
docs/source/user_guide/09_submitting_assignments.ipynb
docs/source/user_guide/10_collecting_assignments.ipynb
docs/source/user_guide/11_jupyterhub_config.rst
docs/source/user_guide/jupyterhub/jupyterhub_config.py
docs/source/user_guide/jupyterhub/nbgrader_config.py

* Closes #391 
* Closes #382
@jonathanmorgan could you have a look at this and tell me if these changes answer your questions?

Add some clarifications to the docs

---

nbgrader/nbextensions/assignment_list/static/assignment_list.js
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py

Ensure that div ids in the assignment list only use valid characters

---

nbgrader/apps/releaseapp.py

nbgrader release typo

---

nbgrader/apps/formgradeapp.py
nbgrader/formgrader/handlers.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py

#395 didn't properly update the formgrader to use the course directory, this fixes that.

Fix formgrader to use course directory

---

nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/formgrader/test_auth_failures.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

This adds tests for integration with JupyterHub when it is using SSL. Basically this is just the tests from #410

Add tests for https

---

nbgrader/nbextensions/create_assignment/create_assignment.css

I think it should do the trick, but my installation is broken for whatever reason and safari give weird result even with the fix I did  yesterday, so I'm not sure. 
Fixes #394

Fix bad celltoolbar flex layout

---

nbgrader/apps/baseapp.py
nbgrader/apps/submitapp.py
nbgrader/tests/apps/test_nbgrader_submit.py

Make sure perms are set correctly by nbgrader submit

---

nbgrader/apps/autogradeapp.py
nbgrader/tests/apps/files/test-with-output.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py

Add --no-execute flag to autogradeapp.py

---

nbgrader/apps/baseapp.py
nbgrader/apps/submitapp.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py

Allow --assignment flag to be used with transfer apps

---

docs/source/index.rst

Add summary and links to resources in docs

---

nbgrader/preprocessors/execute.py

Test that other kernels work with nbgrader

---

docs/source/index.rst
docs/source/user_guide/highlights.rst

Fixes #459 
@willingc does this address your suggestions well enough? I also fleshed out the README in the demo repository so it should be clearer what people should do with it.

Add more prominent links to demo

---

conda.recipe/meta.yaml
requirements.txt

Just temporarily so I can merge #489

Temporarily pin to notebook 4.1

---

nbgrader/formgrader/handlers.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

Fixes #487 and adds a regression test

Make sure next/prev buttons use correct base_url

---

nbgrader/docs/source/configuration/jupyterhub/nbgrader_config.py
nbgrader/docs/source/configuration/jupyterhub_config.rst

Remove generate_hubapi_token from docs

---

conda.recipe/meta.yaml
nbgrader/preprocessors/execute.py
requirements.txt

Raise an error on iopub timeout

---

.gitignore
dev-requirements.txt
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/command_line_tools/index.rst
nbgrader/docs/source/contributor_guide/releasing.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/tests/formgrader/conftest.py
requirements.txt
scripts/nbgrader
setup.py
tools/changelog.py
tools/contributer_list.py
tools/gh_api.py
tools/release.py

Ping @willingc for docs review
This streamlines the workflow for creating a release by adding a few helper scripts and documents all the necessary steps. This is as much for myself as it is for other contributors as I always forget exactly what needs to be done in creating a release 😜

Write documentation on creating releases

---

nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/index.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/autograding_resources.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

Sort of fixes #197
This moves the section on tips for writing good autograder tests to a new file, and expands it with additional wisdom regarding external resources (like plotchecker) and things specifically to look out for when writing autograder tests.

Add a section on autograding wisdom

---

tasks.py

Invoke apparently now requires a context to be passed to all the tasks.

Update to most recent version of invoke

---

nbgrader/apps/extensionapp.py
nbgrader/docs/source/user_guide/installation.rst
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

Update docs on installing extensions

---

nbgrader/docs/source/api/index.rst
nbgrader/docs/source/api/models.rst
nbgrader/docs/source/index.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/extract_grades.py
nbgrader/docs/source/user_guide/faq.rst
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

Add advanced topics section in the docs

---

nbgrader/docs/source/configuration/jupyterhub_config.rst

Document using JupyterHub with SSL

---

nbgrader/api.py
nbgrader/apps/__init__.py
nbgrader/apps/exportapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/command_line_tools/index.rst
nbgrader/docs/source/plugins/export-plugin.rst
nbgrader/docs/source/plugins/index.rst
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/plugins/__init__.py
nbgrader/plugins/export.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/test_nbgrader_export.py

This adds a `nbgrader export` command with the basic functionality to export grades/information from the database to another format. It comes with the ability to be customized with plugins, and comes with a plugin for exporting to CSV by default.
cc @huwf

Create a "nbgrader export" command

---

nbgrader/docs/source/configuration/student_version.rst
nbgrader/docs/source/index.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/faq.rst
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

Document how to customize the student version of an assignment

---

nbgrader/docs/source/configuration/student_version.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb

Add documentation regarding how validation works

---

nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/release/ps1/problem1.ipynb
nbgrader/preprocessors/lockcells.py
nbgrader/tests/preprocessors/test_lockcells.py

Add support for true read-only cells

---

nbgrader/docs/source/contributor_guide/testing.rst

Update docs with invoke test group commands

---

nbgrader/nbextensions/static/assignment_list/assignment_list.js

Fixes #592 
As per @minrk suggestion, use notebooks ajax if >=4.3.1 else jquery ajax.

Send xsrf token in the X-XSRF-Token header for ajax

---

nbgrader/__init__.py
nbgrader/apps/extensionapp.py
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/installation.rst
nbgrader/nbextensions/assignment_list/handlers.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/nbextensions/conftest.py

Revert "Use jupyter nbextension/serverextension for installation/activation"

---

conda.recipe/bld.bat
conda.recipe/build.sh
conda.recipe/post-link.bat
conda.recipe/post-link.sh
conda.recipe/pre-unlink.bat
conda.recipe/pre-unlink.sh
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/installation.rst

Closes #595 
@ellisonbg, @jhamrick I also updated the docs a bit if you wouldn't mind checking them again.

Conda recipe - nbextension link / unlink scripts

---

tasks.py

Add shell config for invoke on windows

---

nbgrader/auth/base.py

Set instance variables in base auth class before running super init

---

nbgrader/docs/source/user_guide/faq.rst

Update FAQ with platform information

---

nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem2.ipynb
nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem2.ipynb
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/release/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/release/ps1/problem2.ipynb

I forgot to rebuild them after merging #611

Rebuild docs

---

nbgrader/api.py
nbgrader/formgrader/handlers.py
nbgrader/formgrader/static/css/formgrade.css
nbgrader/formgrader/templates/formgrade.tpl
nbgrader/formgrader/templates/formgrade_macros.tpl
nbgrader/formgrader/templates/gradebook.tpl
nbgrader/formgrader/templates/notebook_submissions.tpl
nbgrader/tests/api/test_models.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

Fixes #575 
This is what the new behavior looks like:

Add ability to show student names in formgrader

---

.travis.yml

Assuming all the tests pass, I will merge this in for the next milestone.

Add CI tests for python 3.6

---

nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/faq.rst

Document when needs manual grade is set

---

setup.py

Make sure to include schema files

---

.gitignore
nbgrader/apps/__init__.py
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/dbapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/command_line_tools/index.rst
nbgrader/docs/source/index.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb
nbgrader/docs/source/user_guide/managing_the_database.rst
nbgrader/docs/source/user_guide/philosophy.rst
nbgrader/tests/apps/test_nbgrader_db.py

Fixes #624
This is just my initial implementation so far. I still need to:
cc @ellisonbg

Add "nbgrader db" app for modifying the database

---

conda.recipe/meta.yaml
dev-requirements-windows.txt
dev-requirements.txt
nbgrader/_version.py
nbgrader/apps/notebookapp.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/contributor_guide/installation_developer.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/nbextensions/static/assignment_list/assignment_list.js
nbgrader/tests/nbextensions/conftest.py
tasks.py

@lgpage this includes all the fixes so far needed for building on conda-forge, with the exception of #599 which I will tackle next (and before I merge this PR). 
Fixes #602

Create 0.3.2 release

---

setup.py

Fixes #632 
Credit to @ellisonbg

Remove extra level of depth in schema per @ellisonbg

---

README.md

I just noticed I forgot to update the conda channel in the README :(

Update conda channel to conda-forge

---

nbgrader/apps/baseapp.py

Print warning when no config file is found

---

nbgrader/docs/source/contributor_guide/installation_developer.rst

Update developer installation docs

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/auth/hubauth.py
nbgrader/preprocessors/clearsolutions.py

Fix deprecation warnings for config options

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Undeprecate --create in assign and autograde

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Backport PR #672: Undeprecate --create in assign and autograde

---

nbgrader/preprocessors/getgrades.py

Add display_data_priority option to GetGrades preprocessor

---

nbgrader/apps/baseapp.py

Add cwd to path for all nbgrader apps

---

nbgrader/apps/baseapp.py
nbgrader/apps/releaseapp.py
nbgrader/apps/submitapp.py

Make sure the correct permissions are set on released assignments

---

nbgrader/tests/formgrader/conftest.py
nbgrader/tests/nbextensions/conftest.py

Hopefully this will make the windows tests less flaky?
cf #649 
cc @lgpage

Set proxy-type=none in phantomjs

---

nbgrader/nbextensions/assignment_list/assignment_list.js
nbgrader/nbextensions/assignment_list/main.js
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/tests/nbextensions/test_create_assignment.py

This sets the course element (`course_list_default`) text before loading assignments and splits the test wait into two part:
- wait for courses to be loaded, then
- wait for assignments to be loaded
Should fix #694 properly.

Fix nbextension tests

---

nbgrader/docs/source/configuration/student_version.rst

Update docs regarding solution delimeters

---

nbgrader/api.py
nbgrader/apps/autogradeapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/overwritekernelspec.py
nbgrader/preprocessors/savecells.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/preprocessors/test_overwritekernelspec.py
nbgrader/tests/preprocessors/test_savecells.py

@jhamrick what do you think about this for #417

Preserve kernelspec when autograding

---

nbgrader/apps/zipcollectapp.py
nbgrader/tests/apps/test_nbgrader_zip_collect.py

Fix the collecting of submission files for multiple attempts of multiple notebook assignments

---

nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/handlers.py

Refactor the filtering of existing submission notebooks for formgrader

---

nbgrader/apps/baseapp.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Skip over students with empty submissions

---

nbgrader/apps/exportapp.py
nbgrader/apps/zipcollectapp.py
nbgrader/tests/apps/files/myexporter.py
nbgrader/tests/apps/test_nbgrader_export.py

Fix bug with --to in custom exporters

---

nbgrader/coursedir.py

Add documentation for how to pass numeric ids

---

nbgrader/apps/zipcollectapp.py
nbgrader/plugins/zipcollect.py

Add some more informative error messages in zip collect

---

nbgrader/exchange/exchange.py
nbgrader/exchange/fetch.py
nbgrader/exchange/release.py
nbgrader/exchange/submit.py
nbgrader/tests/apps/test_nbgrader_collect.py

Set correct permissions when submitting assignments

---

nbgrader/tests/nbextensions/test_create_assignment.py

Should hopefully address part of #694

More robust saving of the notebook in create assignment tests

---

nbgrader/__init__.py
nbgrader/nbextensions/assignment_list/assignment_list.js
nbgrader/nbextensions/validate_assignment/main.js
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/server_extensions/validate_assignment/__init__.py
nbgrader/server_extensions/validate_assignment/handlers.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/files/submitted-changed.ipynb
nbgrader/tests/nbextensions/files/submitted-grade-cell-changed.ipynb
nbgrader/tests/nbextensions/files/submitted-locked-cell-changed.ipynb
nbgrader/tests/nbextensions/files/submitted-unchanged.ipynb
nbgrader/tests/nbextensions/test_validate_assignment.py

Fixes #569 
This adds a "validate" button to the notebook view that runs `nbgrader validate` in the background:

Validate assignment extension

---

nbgrader/apps/validateapp.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/validator.py

Make sure validation works with notebook globs

---

nbgrader/alembic/env.py
nbgrader/alembic/versions/724cde206c17_add_extra_credit_column.py
nbgrader/api.py
nbgrader/docs/source/api/models.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/server_extensions/formgrader/apihandlers.py
nbgrader/server_extensions/formgrader/static/css/formgrade.css
nbgrader/server_extensions/formgrader/static/js/models.js
nbgrader/server_extensions/formgrader/templates/formgrade.tpl
nbgrader/tests/api/test_models.py
nbgrader/tests/nbextensions/formgrade_utils.py
nbgrader/tests/nbextensions/test_formgrader.py

Fixes #488 
This adds a new column to the database and then adds a field in the formgrader for assigning extra credit:
This extra credit gets added to the total score of the notebook when generating feedback, allowing it to exceed the max score:
cc @ellisonbg @dlsun

Extra credit

---

nbgrader/apps/validateapp.py
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb
nbgrader/tests/apps/test_nbgrader_validate.py

Fix nbgrader validate globbing for real this time

---

nbgrader/server_extensions/formgrader/templates/formgrade.tpl

Fix mathjax rendering

---

nbgrader/apps/baseapp.py
nbgrader/apps/nbgraderapp.py

Includes config options that I forgot to add in #772

Add missing config options

---

nbgrader/exchange/release.py
nbgrader/tests/apps/test_nbgrader_release.py

Create and set permissions for exchange directory when using `nbgrader release`

---

nbgrader/api.py
nbgrader/apps/__init__.py
nbgrader/apps/api.py
nbgrader/apps/baseapp.py
nbgrader/converters/assign.py
nbgrader/converters/base.py
nbgrader/docs/source/api/high_level_api.rst
nbgrader/docs/source/api/index.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/exchange/collect.py
nbgrader/exchange/exchange.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_api.py
nbgrader/utils.py

This is a necessary component for #555 . This API provides high-level functionality for most of the core apps. In the future, we can also add functionality for other apps but this is the core minimum required for creating the webapp. Example usage:
```python
config = Config()
config.Exchange.course_id = "course101"
coursedir = CourseDirectory(config=config)
api = NbGraderAPI(coursedir, config=config)
api.assign("ps1")
print(api.get_assignment("ps1")) # prints a dictionary of information about ps1
api.release("ps1")
api.collect("ps1")
api.autograde("ps1", "foo")
print(api.get_submission("ps1", "foo")) # prints a dictionary of information about foo's submitted ps1
```
Need to add documentation still.

Create a new high-level python API for nbgrader

---

nbgrader/converters/autograde.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Currently, missing notebooks get an implicit score of zero (the default) and are marked as needing manual grading. However, it is impossible to manually grade a missing notebook. This PR detects notebooks that are missing and assigns them an explicit autograded score of 0 and also marks them as not needing manual grading.

Assign missing notebooks a score of zero and mark as not needing grading

---

nbgrader/_version.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/conf.py
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb

Release of 0.5.0

---

nbgrader/_version.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb

Release 0.5.1

---

nbgrader/docs/source/user_guide/installation.rst

This solves issue #817, updating the install instructions for the conda-forge package.

Update install instructions

---

nbgrader/docs/source/user_guide/faq.rst

Add FAQ sections

---

nbgrader/docs/source/user_guide/philosophy.rst

Add directory structure example

---

nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

Fix typo on Managing assignment docs

---

nbgrader/apps/quickstartapp.py

Include quickstart .ipynb header

---

nbgrader/docs/source/contributor_guide/releasing.rst
nbgrader/nbextensions/assignment_list/assignment_list.css
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/validate_assignment/main.js
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/server_extensions/formgrader/apihandlers.py
nbgrader/server_extensions/validate_assignment/handlers.py

Fixes #804
This will display errors both on the command line, and in the browser, if the nbextension version does not match the server extension version in the Assignment List or the Validate extensions.

Report mismatch extension versions

---

nbgrader/converters/base.py

Always raise on convert failure

---

nbgrader/apps/baseapp.py
nbgrader/apps/dbapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_db.py

Print out app subcommands by default

---

nbgrader/apps/fetchapp.py
nbgrader/tests/apps/test_nbgrader_fetch.py

Fetch multiple assignments in one command

---

nbgrader/__init__.py
nbgrader/tests/apps/test_nbgrader_extension.py

Don't install assignment list on windows

---

nbgrader/docs/source/contributor_guide/metadata.rst
nbgrader/nbextensions/create_assignment/main.js
nbgrader/nbgraderformat/v1.py
nbgrader/tests/nbextensions/test_create_assignment.py
nbgrader/tests/nbgraderformat/test_v1.py

Disallow negative point values

---

nbgrader/server_extensions/formgrader/formgrader.py

Fix html export config options to avoid warnings

---

README.md
nbgrader/docs/source/index.rst

Add links to the scipy talk

---

nbgrader/server_extensions/formgrader/handlers.py
nbgrader/server_extensions/formgrader/static/js/gradebook_notebook_submissions.js
nbgrader/server_extensions/formgrader/templates/formgrade_macros.tpl

Reveal ids if names aren't set

---

nbgrader/converters/feedback.py

Include extension with feedback template filename

---

nbgrader/_version.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/validate_assignment/main.js

I am going to wait until #806 is fixed to actually release this, I am making the PR now anyway just to get the other changes that need to happen out of the way.

Release 0.5.2

---

nbgrader/converters/base.py
nbgrader/preprocessors/headerfooter.py
nbgrader/tests/apps/test_nbgrader_assign.py

Change to the root of the course directory before running nbgrader converters

---

nbgrader/preprocessors/overwritekernelspec.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Fix overwritekernelspec preprocessor and update tests

---

nbgrader/server_extensions/validate_assignment/handlers.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/files/data.txt
nbgrader/tests/nbextensions/files/open_relative_file.ipynb
nbgrader/tests/nbextensions/test_validate_assignment.py
nbgrader/utils.py
nbgrader/validator.py

fix #879 
I would like to add some tests, however, it is totally out of my ability. Have no idea how `invoke` works.

change directory when validating notebooks

---

nbgrader/server_extensions/validate_assignment/handlers.py

Fixes #891 
Thanks to @randy3k for isolating the problem!

Make sure validation is run in the correct directory

---

nbgrader/apps/dbapp.py
nbgrader/tests/apps/test_nbgrader_db.py

creates private method for preprocessing keys for any future transforms
that are needed
Closes #890.

Add test and fix for parsing csv key names with spaces

---

nbgrader/apps/dbapp.py

This doesn't make much sense without #895, so it is built off of it. 
adds help docs that inspect the column names.

Help for csv import

---

.github/issue_template.md

Written with @jhamrick's approval.

Improve issue template to explain logic behind filling it out

---

nbgrader/_version.py
nbgrader/api.py
nbgrader/apps/dbapp.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb
nbgrader/docs/source/user_guide/managing_the_database.ipynb
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/validate_assignment/main.js
nbgrader/preprocessors/overwritekernelspec.py
nbgrader/server_extensions/validate_assignment/handlers.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_db.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/files/data.txt
nbgrader/tests/nbextensions/files/open_relative_file.ipynb
nbgrader/tests/nbextensions/test_validate_assignment.py
nbgrader/utils.py
nbgrader/validator.py

Fixes #885 but I would like to wait until #890 and #891 are fixed before actually making the release.

Release 0.5.4

---

nbgrader/docs/source/configuration/jupyterhub_config.rst

Fixes #881 
I try to go into much more detail here about different ways you could set up the formgrader and jupyterhub. Hopefully this clears up some of the confusion about how to get it to work. I would appreciate if you have any feedback @kthyng @yao2001626 @dsblank @reckoner

Give more details on how to use formgrader and jupyterhub

---

nbgrader/apps/updateapp.py
nbgrader/apps/validateapp.py
nbgrader/converters/base.py
nbgrader/nbextensions/create_assignment/main.js
nbgrader/nbgraderformat/__init__.py
nbgrader/nbgraderformat/common.py
nbgrader/preprocessors/checkcellmetadata.py
nbgrader/server_extensions/validate_assignment/handlers.py

Friendlier error messages when encountering a schema mismatch

---

tasks.py

* Fix test option to be --reruns, rather than --rerun

Fix failing tests

---

nbgrader/coursedir.py
nbgrader/exchange/exchange.py
nbgrader/server_extensions/formgrader/apihandlers.py
nbgrader/tests/nbextensions/test_formgrader.py

Strip whitespace from assignment, student, and course ids

---

nbgrader/apps/api.py
nbgrader/tests/apps/test_api.py

Should help with #929
@ryanlovett Is it possible for you to test this to see if it helps?

Skip filtering notebooks when ExchangeSubmit.strict == True

---

nbgrader/tests/utils/test_utils.py
nbgrader/utils.py

Fix bug in find_all_files that doesn't properly ignore directories

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/dbapp.py
nbgrader/apps/feedbackapp.py
nbgrader/apps/quickstartapp.py
nbgrader/apps/releaseapp.py
nbgrader/apps/zipcollectapp.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_db.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/apps/test_nbgrader_quickstart.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_zip_collect.py

Allow apps to use -f and --force

---

nbgrader/converters/base.py
nbgrader/exchange/exchange.py
nbgrader/exchange/fetch.py
nbgrader/exchange/release.py
nbgrader/exchange/submit.py
setup.py

Do some amount of fuzzy problem set name matching

---

nbgrader/docs/source/index.rst
nbgrader/docs/source/user_guide/third_party.rst

Add third party resources to the documentation

---

setup.py

To make the code look more pythonic.

Added "if __name__ == "__main__":"

---

nbgrader/docs/source/user_guide/third_party.rst

Solves https://github.com/jupyter/nbgrader/issues/969

Add link to jupyter in education map

---

nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/spelling_wordlist.txt

Fix the link to autodoc documentation and add some words to the spelling list.

Fix broken documentation

---

nbgrader/api.py

just a comment mistake in api.py.

a mistake in comment

---

nbgrader/docs/source/user_guide/installation.rst

Fix of #1015 
I did a quick look and found only anaconda links are broken, Let me know if there are any additional links which are also broken

Fix anaconda link

---

nbgrader/apps/quickstartapp.py
nbgrader/tests/apps/test_nbgrader_quickstart.py

@jhamrick Please let me know if I need to change something.
Thanks! =)
Fixes #818

Make nbgrader quickstart work with existing directories

---

nbgrader/tests/nbextensions/test_formgrader.py

I give up on figuring out why this test keeps failing, so marking it as flaky for now. I will create an issue and hopefully either I or someone else can debug this more in the future.

Mark test_same_part_navigation as flaky

---

tools/contributer_list.py

* Include open and closed issues
* Add option to list contributors for all milestones, not just one

Some improvements to the contributor list script

---

.travis.yml
dev-requirements-windows.txt

- remove cov-core per @jedbrown #1045 
- add more recent python versions
- update to newer travis build parameters

Update test builds on Travis

---

.travis.yml
appveyor.yml
dev-requirements.txt
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/contributor_guide/js_dependencies.rst
nbgrader/docs/source/contributor_guide/releasing.rst
nbgrader/docs/source/contributor_guide/testing.rst
tasks.py

Fixes #1046
cc @jedbrown @willingc

Remove changes to sitecustomize.py and dependency on invoke

---

nbgrader/apps/exportapp.py
nbgrader/plugins/export.py
nbgrader/tests/apps/test_nbgrader_export.py

fixes #799 
The student and assignment option can both be a set of values. Making it possible to export almost all students and / or assignments.

student and assignment selection in exportapp implemented

---

.travis.yml
appveyor.yml

Only build docs with one version of python

---

.travis.yml
appveyor.yml
setup.py

Remove testing of python 3.4

---

nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/utils/conftest.py
nbgrader/tests/utils/test_utils.py

By the way: adds a consistency test for get_username.

Systematic use of utils.get_username instead of $USER

---

nbgrader/server_extensions/formgrader/apihandlers.py
nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/formgrader.py
nbgrader/server_extensions/formgrader/handlers.py

Fixes #1012
This will also return an error page in the formgrader, so the configuration error is more obvious.

Check that the course directory is a subdirectory of the notebook dir

---

nbgrader/docs/source/build_docs.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/configuration/nbgrader_config.rst
nbgrader/docs/source/configuration/student_version.rst
nbgrader/docs/source/index.rst

Better documentation of nbgrader_config.py

---

nbgrader/nbextensions/create_assignment/main.js
nbgrader/tests/nbextensions/test_create_assignment.py

Ensure that cell type changes result in valid nbgrader metadata

---

nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
nbgrader/api.py
nbgrader/tests/api/test_gradebook.py

This will add a course table and a foreign key from the assignment table into the course table.
Closes #960

Add course table, add course_id column to assignment

---

nbgrader/apps/__init__.py
nbgrader/apps/api.py
nbgrader/apps/feedbackapp.py
nbgrader/apps/generatefeedbackapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/apps/releasefeedbackapp.py
nbgrader/converters/__init__.py
nbgrader/converters/base.py
nbgrader/converters/feedback.py
nbgrader/converters/generate_feedback.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/command_line_tools/index.rst
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/configuration/student_version.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/faq.rst
nbgrader/docs/source/user_guide/highlights.rst
nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
nbgrader/tests/apps/test_nbgrader_generate_feedback.py
nbgrader/tests/apps/test_nbgrader_releasefeedback.py

Rename nbgrader feedback to nbgrader generate_feedback

---

nbgrader/nbextensions/create_assignment/main.js

Fix minor typo in js extension helper text

---

nbgrader/_version.py
nbgrader/docs/source/changelog.rst
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/validate_assignment/main.js
setup.py

Make 0.5.6 release

---

nbgrader/exchange/fetch_feedback.py
nbgrader/tests/apps/test_api.py
nbgrader/tests/apps/test_nbgrader_fetchfeedback.py

There might be some tests that need to be checked, but I put this as initial starting point.
Issue was talked in here #1120 
Discussion welcome and required.

Remove student_id and change root to cache, permission check to only execute

---

nbgrader/apps/fetchfeedbackapp.py

- I don't really know if everthing in this description update is
correct, but I did the best I could.  Please sanity-check first.
- As noticed by @sefriol

Feedback: update fetch_feedback command line help

---

demos/README.md
demos/demo_multiple_classes/course101_nbgrader_config.py
demos/demo_multiple_classes/course123_nbgrader_config.py
demos/demo_multiple_classes/global_nbgrader_config.py
demos/demo_multiple_classes/jupyterhub_config.py
demos/demo_multiple_classes/setup_demo.sh
demos/demo_one_class_multiple_graders/course101_nbgrader_config.py
demos/demo_one_class_multiple_graders/global_nbgrader_config.py
demos/demo_one_class_multiple_graders/jupyterhub_config.py
demos/demo_one_class_multiple_graders/setup_demo.sh
demos/demo_one_class_one_grader/instructor_nbgrader_config.py
demos/demo_one_class_one_grader/jupyterhub_config.py
demos/demo_one_class_one_grader/setup_demo.sh
demos/deploy_demos.sh
demos/restart_demo.sh
demos/utils.sh

This creates a directory with some working demos of how to properly configure nbgrader with JupyterHub. This is useful both for for people who are trying to get nbgrader setup, as well as for developing nbgrader and testing out JupyterHub integration with a minimum working example.

Add JupyterHub demos

---

nbgrader/_version.py
nbgrader/apps/fetchassignmentapp.py
nbgrader/apps/fetchfeedbackapp.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/user_guide/faq.rst
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/course_list/main.js
nbgrader/nbextensions/validate_assignment/main.js
tools/contributer_list.py
tools/gh_api.py

It's finally time!! 🎉 
Waiting on merging the last few PRs which are still building, then I will merge this and make the release (likely will be tomorrow, as the tests are rather backed up at the moment).
Closes #1107

Create 0.6.0 release

---

nbgrader/exchange/list.py
nbgrader/nbextensions/assignment_list/assignment_list.js
nbgrader/tests/apps/test_nbgrader_list.py

If feedback exists both locally and in the exchange, compute the checksums of both feedback files and compare them. If they're different, then report that newer feedback can be fetched.
Closes: #1201

Check for newer feedback in nbgrader list

---

nbgrader/apps/api.py
nbgrader/tests/apps/test_api.py

Fixes the first problem in #1201

Force generate feedback by default in API

---

nbgrader/apps/api.py
nbgrader/apps/zipcollectapp.py
nbgrader/docs/source/build_docs.py
nbgrader/server_extensions/course_list/handlers.py
nbgrader/tests/__init__.py
nbgrader/tests/nbextensions/formgrade_utils.py
nbgrader/tests/test_validator.py
nbgrader/utils.py
setup.py
tools/backport_pr.py

Removing references to six and a couple of python 2 imports
Fixes #1251

Remove Python 2 compatibility code

---

dev-requirements.txt
nbgrader/api.py
nbgrader/docs/source/conf.py

Type annotations for the api

---

nbgrader/server_extensions/assignment_list/handlers.py

Improves the error message on the assignments page in the case that there is an ExchangeError.

Improve the error message on the assignments page

---

nbgrader/apps/baseapp.py
nbgrader/apps/quickstartapp.py
nbgrader/converters/autograde.py
nbgrader/converters/generate_assignment.py
nbgrader/coursedir.py
nbgrader/docs/source/user_guide/managing_the_database.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_export.py
nbgrader/tests/apps/test_nbgrader_fetchfeedback.py
nbgrader/tests/apps/test_nbgrader_generate_assignment.py
nbgrader/tests/apps/test_nbgrader_generate_feedback.py
nbgrader/tests/apps/test_nbgrader_releasefeedback.py
nbgrader/tests/apps/test_nbgrader_update.py
nbgrader/tests/apps/test_nbgrader_zip_collect.py
nbgrader/tests/nbextensions/conftest.py

remove db_assignments db_students

---

nbgrader/auth/base.py
nbgrader/auth/jupyterhub.py
nbgrader/server_extensions/course_list/handlers.py
nbgrader/tests/test_auth.py

Improve test coverage in auth folder

---

nbgrader/nbextensions/course_list/course_list.js
nbgrader/server_extensions/course_list/handlers.py

Fix course list hanging when exchange has not been created 

---

.travis.yml
azure-pipelines.yml
nbgrader/api.py
nbgrader/tests/api/test_models.py

Fix inappropriate use of sum with newer sqlite

---

nbgrader/_version.py
nbgrader/docs/source/changelog.rst
nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/course_list/main.js
nbgrader/nbextensions/validate_assignment/main.js

Waiting on #1284 and #1285 to be merged first.

Create 0.6.1 release

---

.travis.yml
dev-requirements.txt
tasks.py

- Drop 3.5
- Disable mypy
- allow nightly to fail

Update the test matrix on Travis to Python 3.6+

---

dev-requirements.txt
setup.py

Pin nbconvert to 5.6.1, traitlets to 4.3.3 and pytest to <6.0.0

---

nbgrader/docs/source/index.rst
nbgrader/docs/source/user_guide/what_is_nbgrader.rst

Following my pattern in writing a "what is jupyterhub?", I've written
a "what is nbgrader?".  This goes into the technical details of what
is happening under the nbgrader hood, which is an important way for
people to self-support.  It's also what I was looking for when I was
first starting out with nbgrader, and had to piece together by reading
the implicit information on all of the other pages.  I also think this
is important when we are moving towards more advance development.
But, this is not complete yet.  I started several months ago and never
got to detailed proofreading or even finishing it.  So that it's not
lost forever, I'm making a PR with it and hope that others can help to
improve it.
To review: everything, both content and text.  Especially pay
attention to fact-checking …

Description of "what is nbgrader?"

---

nbgrader/converters/autograde.py
nbgrader/converters/base.py
nbgrader/converters/generate_assignment.py
nbgrader/converters/generate_feedback.py

This would allow users to add custom preprocessors to the autograde and generate assignment converters without maintaining a fork of nbgrader. 
Any comments are appreciated.

Make preprocessors of generate assignment, autograde and generate feedback configurable

---

nbgrader/api.py

- Adds the rollback() operation to try/except clauses in the [Gradebook class](https://github.com/jupyter/nbgrader/blob/master/nbgrader/api.py#L1300).
- Adds exception logging for rollback operation
Closes #1451

Add missing rollbacks to try/except clauses that execute db commits

---

setup.py

- Updates setup.py to remove locks to minor/patch versions of the dependencies
- Replaces locked dependencies with dependency ranges
Closes #1538 
cc/ @BertR @rkdarst

Update setup.py with dependency ranges

---

nbgrader/converters/generate_solution.py

Most preprocessors were made configurable but not for the generate_solutions converter.
see #1376

Make generate solutions preprocessors configurable

---

nbgrader/converters/autograde.py

Revert "[converters/autograde] Fix autograded notebook permission"

---

setup.cfg

looks like it was added by mistake in #1541

Don't depend on qtconsole

---

nbgrader/docs/source/contributor_guide/testing.rst

Add documentation to run tests on labextensions

Add instruction to run playwright tests

---

nbgrader/tests/labextension_ui-tests/tests/test_assignment_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_course_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_create_assignement.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_utils.ts
nbgrader/tests/labextension_ui-tests/tests/test_validate_assignment.spec.ts

Some variables where used as string but could be undefined in the labextension tests.
This PR add some missing checks on that.

Fix some typo and variable declaration in labextension tests

---

.github/workflows/check-release.yml
pyproject.toml

Update to Jupyter Releaser v2

---

nbgrader/tests/nbextensions/conftest.py

Relevant: https://github.com/SeleniumHQ/selenium/issues/12185

Fix selenium deprecation for nbextension tests

---

nbgrader/docs/make.bat
nbgrader/docs/source/conf.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/contributor_guide/database.rst
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/contributor_guide/overview.rst
nbgrader/docs/source/contributor_guide/pull_request.rst
nbgrader/docs/source/contributor_guide/releasing.rst
nbgrader/docs/source/plugins/zipcollect-plugin.rst

Fix broken and redirected links in documentation.

Fix documentation links

---

binder/postBuild

Fix the exchange directory in the example used in binder, to be able to fetch assignments

Fix binder exchange

---

package.json
pyproject.toml
yarn.lock

Update the notebook dependency to `v7.0.0`

Update notebook dependency to final release

---

demos/restart_demo.sh
nbgrader/docs/source/user_guide/installation.rst

See https://github.com/jupyter/nbgrader/discussions/1749#discussioncomment-6709943

Fix labextension plutin IDs in the docs

---

demos/restart_demo.sh
demos/utils.sh
nbgrader/docs/source/user_guide/installation.rst

https://github.com/jupyter/nbgrader/pull/1811 has happened again :facepalm: 
This fixes https://github.com/jupyter/nbgrader/pull/1893

Fix labextension plugin IDs in the docs and demos
