nbgrader/html/static/css/formgrade.css
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl

A few things to (hopefully) significantly improve the grading experience with the formgrader, including:
* making it clearer which score/comment fields go with which cells
* automatic scrolling to the first score/comment field
* smooth scrolling to the next score/comment field when tab is pressed
* press shift+right arrow to move to the same field in the next student's assignment, or shift+left arrow to move to the same field in the previous student's assignment
* cycle back to the first score/comment field after the last
Example of tabbing and moving between assignments (when the page looks like it is refreshing, that is actually moving to a different submission):

Formgrader UI improvements

---

docs/command_line_tools/nbgrader assign.ipynb
docs/command_line_tools/nbgrader autograde.ipynb
docs/command_line_tools/nbgrader validate.ipynb
docs/user_guide/3 - Releasing assignments.ipynb
docs/user_guide/4 - Autograding.ipynb
docs/user_guide/grade_example/autograded/Bitdiddle/Problem 1.ipynb
docs/user_guide/grade_example/autograded/Hacker/Problem 1.ipynb
nbgrader/apps/autogradeapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/execute.py

This creates a modified version of the execute preprocessor that will (1) not allow standard input, and (2) timeout on long running cells with a kernel interrupt and continue running cells after that. With these two changes, if students leave `%debug` or `%raw_input` statements in their code, or if they have infinite loops/recursion, it won't cause the autograder to break.
Fixes #70

Timeout on long-running cells

---

nbgrader/api.py

Currently, if there is floating point error when computing the max score, an error is thrown in the formgrader which prevents it from being used at all. This changes it to a warning which is a little nicer.

Warn about there being more than one max score

---

nbgrader/preprocessors/execute.py

Otherwise, nbgrader can't be run in parallel because the different threads try to use the same history file.

Use memory for ipython kernel history

---

nbgrader/apps/formgradeapp.py
nbgrader/apps/notebookapp.py
nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/notebook_submissions.tpl

This sorts submissions by submission id, rather than by student id, and does not display the student id in the grading interface. This is better, because when you are just going through and grading all assignments, it is better for the order to be randomized and for the student names to be anonymized. However, this presents a challenge, which is that it makes it impossible to manually open the student's notebook in a live notebook server -- so this additionally adds functionality to launch a notebook server along with the formgrader, and a link to open the live notebook if so desired.
* Fixes #84
* Fixes #85

Anonymize students and add notebook link

---

.travis.yml
README.md
requirements.txt

Previously we always installed from dev, but now that IPython 3 is out, we should just depend on that.

Update required ipython version

---

nbgrader/api.py
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/computechecksums.py
nbgrader/preprocessors/overwritecells.py
nbgrader/preprocessors/savecells.py
nbgrader/tests/base.py
nbgrader/tests/test_api.py
nbgrader/tests/test_computechecksums.py
nbgrader/tests/test_gradebook.py
nbgrader/tests/test_overwritecells.py
nbgrader/tests/test_savecells.py
nbgrader/tests/test_utils.py
nbgrader/utils.py

This updates the `SaveCells` preprocessor (formerly `SaveGradeCells`) to save the cell type of solution cells as well as grade cells, and updates the `OverwriteCells` preprocessor (formerly `OverwriteGradeCells`) to update the cell type of solutions cells. It also saves the source and checksum of solution cells, though nothing is (currently) done with that information.
* Fixes #116 
* Fixes #114 
* Fixes #107

Check solution cell type

---

nbgrader/preprocessors/displayautogrades.py
nbgrader/utils.py

`nbgrader validate` should still work, even if there are no checksums in the cell metadata.

Fix checksums in nbgrader validate

---

nbgrader/apps/assignapp.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/checkcellmetadata.py
nbgrader/preprocessors/clearsolutions.py
nbgrader/tests/files/bad-code-cell.ipynb
nbgrader/tests/files/bad-markdown-cell-1.ipynb
nbgrader/tests/files/bad-markdown-cell-2.ipynb
nbgrader/tests/test_checkcellmetadata.py
nbgrader/tests/test_clearsolutions.py

This checks that code cells are either solution or grade cells (but not both) and that markdown cells are both solution and grade (or neither). It also adds functionality to mark cells with solution regions as solution cells in `nbgrader assign`.
* Fixes #69 
* Fixes #110

Check cell types

---

nbgrader/preprocessors/displayautogrades.py
nbgrader/tests/test_nbgrader_validate.py

This is so that if the way of computing checksums has changed since an assignment was released, `nbgrader validate` can be made to ignore checksums so it doesn't alarm the students.

Optionally ignore checksums in nbgrader validate

---

requirements.txt

Unpinning ipython version to allow to work with 3.0 and 3.1, etc.

---

docs/user_guide/1 - Installing.ipynb
nbgrader/install.py

make `profile` first positional arg, + add docs on installing.
It occurred to me that install might not actually require a profile name as it can install globally on the system.

make profile ags mandatory + docs

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/feedbackapp.py
nbgrader/apps/formgradeapp.py
nbgrader/config.py

Rather than having the apps have `nbgrader_input_step_name` and `nbgrader_output_step_name` config variables, make a config options in `NbGraderConfig` for the common set of directories:
* `source_directory`
* `release_directory`
* `submitted_directory`
* `autograded_directory`
* `feedback_directory`
That way if the directory name is changed, all the apps that rely on that directory will know about it. For example, apps that inherit from `BaseNbConvertApp` can define `_input_directory` and `_output_directory` properties that return one of these common directories. 
ping @ellisonbg

Make input and output directories depend on a common config

---

nbgrader/api.py
nbgrader/apps/autogradeapp.py
nbgrader/preprocessors/saveautogrades.py
nbgrader/tests/test_nbgrader_autograde.py
nbgrader/utils.py

Currently the database will automatically remove any timezone info from datetime objects, without properly converting those objects to UTC first. This adds functionality to make sure all timestamps are properly converted to UTC before being saved into the database. This also fixes a bug where when you try to update the timestamp, you get a `TypeError: can't compare offset-naive and offset-aware datetimes` error.
This won't get around the possibility that you could still do something like:
```
assignment = gb.find_assignment("Problem Set 1")
assignment.duedate = dateutil.parser.parse("2015-02-02 14:58:23.948203 PST")
gb.db.commit()
```
in which case the PST timezone would just be removed. The correct way to do it would be:
```
gb.update_or_create_assignment("Problem Set 1", …
```

Save timestamps into database as UTC

---

nbgrader/apps/assignapp.py
nbgrader/tests/test_nbgrader_assign.py

Fixes #171
This should probably use the `self.fail` function that will be added by #200 , so either this should wait for that to be merged, or #200 will need to make some further changes to use `self.fail`.

Add force flag to overwrite assignments

---

nbgrader/install.py
nbgrader/tests/test_nbextension.py

This removes the argparse stuff for installing the nbextension and replaces it with a subclass of `NBExtensionApp`, so that it inherits all the functionality that IPython provides when installing nbextensions. The functions for activating and deactivating the extension are moved into this class.
* Fixes #206
* Fixes #205 
ping @ellisonbg @Carreau

Turn nbextension installation into an ipython app

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/collectapp.py
nbgrader/preprocessors/saveautogrades.py
nbgrader/tests/test_getgrades.py
nbgrader/tests/test_nbgrader_assign.py
nbgrader/tests/test_nbgrader_autograde.py
nbgrader/tests/test_nbgrader_feedback.py
nbgrader/tests/test_saveautogrades.py
nbgrader/tests/test_utils.py
nbgrader/utils.py

This makes it possible for all steps of the nbgrader pipeline that inherit from `BaseNbConvertApp` to skip processing an assignment if it's already been processed. Additionally, this adds a `--force` flag to all these steps so that the assignment can be overwritten if so desired. This PR also centralizes some of stuff that only needs to happen once per assignment -- for example, extra files should be copied over once for the whole assignment, rather than per notebook.
Fixes #173

Skip already processed assignments

---

nbgrader/auth/hubauth.py
nbgrader/tests/test_nbgrader_formgrade_hubauth.py

Changes the default formgrade hub url to `/hub/{{course_id}}`.
Allows more than one formgrade to run behind JupyterHub.  
URL can also be set explicitly.
i.e.  
`https://myhub.com/hub/{{course_id}}` can be changed to  
`https://myhub.com/hub/bgranger-grading` so more classes like  
`https://myhub.com/hub/jhamrick-grading` can be added.  
cc @ellisonbg   
EDIT: 4/6/2015 to reflect current state.

Make the remapped sub-url configurable.

---

nbgrader/apps/baseapp.py
nbgrader/tests/test_nbgrader_autograde.py
nbgrader/tests/test_nbgrader_feedback.py

There were some edge cases in when a submission should be skipped or not that weren't being handled when filtering by notebook. This adds some tests to catch those cases, and fixes them.

Various bugfixes and tests for filtering by notebook

---

nbgrader/auth/noauth.py

Otherwise, if nbgrader is installed with python3 and ipython is not installed on python2, then launching the notebook server for the formgrader will fail.

Run the notebook server with the same python version as nbgrader

---

nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/notebook_submissions.tpl
nbgrader/html/templates/student_submissions.tpl
nbgrader/tests/test_api.py

If students lose points on the code from the autograder, it is nice to be able to give them partial credit. However, if most students got it, then this means you have to navigate through a lot of submissions to get to the ones that lost points. This PR adds a keyboard shortcut (Ctrl+Shift+arrow) to navigate to the next or previous submission that lost points on the coding parts of the problem.
Edit: I also added in a new field to the api indicating whether any tests failed, and then also added a column the formgrader indicating as such.
Fixes #158 
Fixes #95
ping @suchow

Make it possible to navigate to the next/prev incorrect code response

---

nbgrader/apps/autogradeapp.py
nbgrader/tests/base.py
nbgrader/tests/test_nbgrader_autograde.py

This replaces files with their master versions (if they exist in the source directory) when running `nbgrader autograde`. It does this by breaking up the autograding into two steps: first, a "sanitize" step that replaces files, clears outputs, and replaces cells, and second, the actual autograding step where the notebooks are executed and the grades saved into the database.
Fixes #170 
ping @ellisonbg , as I don't want to merge this if it is going to cause any problems for you.

Overwrite files with master version when autograding

---

nbgrader/auth/hubauth.py

Recent changes to JupyterHub have renamed the `user` key to `name` in the response json. This updates the JupyterHub authentication to use `name` instead of `user`.
Ping @ellisonbg and @jdfreder , just FYI. I need to make this change so the tests on travis will pass, but wanted you to be aware of it.

Fix hubauth to work with current jupyterhub

---

nbgrader/html/static/js/formgrade.js

The scrolling in the formgrader can be a bit frustrating if there is a lot of math in the notebook, and mathjax hasn't finished loading yet -- it will execute the scroll, but then the math will finish loading, thus causing the scroll position to be off. This makes it so that the scrolling only happens after mathjax is fully loaded.

Don't scroll until mathjax is loaded

---

nbgrader/auth/base.py
nbgrader/auth/hubauth.py
nbgrader/auth/noauth.py

Fixes #231 
This makes it possible to use `0.0.0.0` for a formgrader running on a remote server. In such a case, the live notebook server won't work, so this additionally prints a warning saying as much and advising the user to change the IP to something that is accessible.

Fix formgrader to work with 0.0.0.0

---

nbgrader/html/static/js/formgrade.js
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/formgrade_macros.tpl
nbgrader/tests/formgrader/test_formgrader.py

Fixes #88 and fixes #83
This allows you to tab to the "next" arrow, and also bring you to the very top of the document, rather than to the first comment/score field.

Improve tabbing experience

---

nbgrader/html/static/css/formgrade.css
nbgrader/html/templates/formgrade.tpl

Fixes #122 and looks like this:
When you hover over the buttons they go back to their original colors.

Better full/no credit button colors

---

nbgrader/html/static/js/formgrade.js

This should fix issues with scrolling to a different part of the page, tabbing to a different window, and tabbing back and then having the formgrader scroll back to the input, which is annoying.

Only scroll to tabbable when it is different from before

---

nbgrader/tests/utils/test_utils.py
nbgrader/utils.py
requirements.txt

Fixes #134 
Ping @ellisonbg because this will break stuff for your students if you are having them use `nbgrader validate`. Let me know if it is ok to merge this (e.g. if you aren't planning on upgrading your version of nbgrader before the class is over, then it should be fine I think).

Remove autopep8 as a dependency

---

nbgrader/nbextensions/nbgrader/create_assignment.js
nbgrader/tests/nbextensions/test_nbextension.py

If the nbgrader cell metadata doesn't exist, it shouldn't be created when the toolbar is loaded -- only when something is actually explicitly set on the metadata.
Fixes #291

Don't automatically set nbgrader cell metadata

---

nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/html/static/css/formgrade.css
nbgrader/html/static/js/models.js
nbgrader/html/templates/assignment_notebooks.tpl
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/notebook_submissions.tpl
nbgrader/html/templates/student_assignments.tpl
nbgrader/html/templates/student_submissions.tpl
nbgrader/preprocessors/saveautogrades.py
nbgrader/tests/api/test_models.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/preprocessors/test_saveautogrades.py

This renames the columns in the formgrader to make it a little clearer what "manual grade?" means, which is that there is a part of the assignment that needs grading.
Edit: this also make the `needs_manual_grade` attribute of the database models be a real column in the database, and modifies the relevant aspects in `nbgrader autograde` and `nbgrader formgrade` to set it.
cc @ellisonbg

Manually set 'needs manual grade?'

---

docs/source/api/models.rst
nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/html/static/css/formgrade.css
nbgrader/html/static/js/formgrade.js
nbgrader/html/static/js/keyboardmanager.js
nbgrader/html/templates/formgrade.tpl
nbgrader/html/templates/notebook_submissions.tpl
nbgrader/html/templates/student_submissions.tpl
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/api/test_models.py
nbgrader/tests/formgrader/test_formgrader_js.py

This adds the ability to flag submissions in the formgrader. I tried to make this as generic as possible, so that instructors can apply whatever meaning they want to the idea of a flag -- e.g., suspicious submission, need someone else to look at it, come back to it later, etc.
Ping @ellisonbg and @jdfreder as this requires adding a new column to one of the database tables. I won't merge this until I have your +1 since I don't want to break stuff for you.

Add submission flags

---

docs/source/api/models.rst
nbgrader/api.py
nbgrader/html/formgrade.py
nbgrader/html/static/js/models.js
nbgrader/html/templates/feedback.tpl
nbgrader/html/templates/formgrade.tpl
nbgrader/preprocessors/getgrades.py
nbgrader/preprocessors/saveautogrades.py
nbgrader/tests/api/test_models.py
nbgrader/tests/preprocessors/test_getgrades.py
nbgrader/tests/preprocessors/test_saveautogrades.py

Fixes #255
This removes the `comment` column from the `Comment` model and replaces it with `auto_comment` and `manual_comment`. This basically makes comments behave just like the score in `Grade` -- there are comments that can be assigned by the autograded, and there are comments that can be assigned by human graders. Manual comments always take precedence.

Separate the notions of automatically assigned comments and manually assigned comments

---

docs/source/api/gradebook.rst
nbgrader/api.py
nbgrader/apps/assignapp.py
nbgrader/preprocessors/savecells.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/preprocessors/test_savecells.py
nbgrader/utils.py

Fixes #208
This will remove information in the database about old notebooks and cells when running `nbgrader assign`, so that if you rerun it you don't end up with some assignments having cells or notebooks associated with them that no longer exist.
The one exception is if there are submissions associated with the assignment already. If this is the case, an error will be thrown if anything is added or removed. Existing cell contents/metadata can be changed, however.

Clear db when running nbgrader assign

---

CONTRIBUTING.md
requirements.txt
tasks.py

Because conda does not preserve package information using ipython[notebook],
developers will need to install ipython notebook separately from other
requirements

Fixing installation requirements and documentation.

---

nbgrader/tests/__init__.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/test_nbgrader_formgrade.py
nbgrader/tests/nbextensions/conftest.py
tasks.py

This modifies the tests so that when they call a subprocess, they never use `shell=True`. Additionally, this now uses `proc.communicate()` instead of `proc.wait()`, which should hopefully fix some deadlock issues that I think we've been having with the travis tests.

Fix subprocess handling in tests

---

nbgrader/apps/collectapp.py
nbgrader/apps/fetchapp.py
nbgrader/apps/listapp.py
nbgrader/apps/releaseapp.py
nbgrader/apps/submitapp.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py

This fixes the transfer apps so that they will fail if a course id is not specified.

Require course id in transfer apps

---

nbgrader/apps/baseapp.py
nbgrader/apps/listapp.py
nbgrader/apps/submitapp.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_submit.py

This modifies the behavior of `nbgrader submit` so that it additionally copies a version of the assignment to a cache directory (by default, `~/.nbgrader/cache`). Then, the `--cached` flag is added to `nbgrader list` so that you can see the list of cached assignments.
This is kind of a workaround to #295. It's not a perfect or ideal solution, but it'll work for the time being until we can implement something more robust like an authenticated REST api for releasing and submitting assignments.
FYI @ellisonbg

Add cache to nbgrader submit and nbgrader list

---

nbgrader/preprocessors/checkcellmetadata.py
nbgrader/preprocessors/overwritecells.py
nbgrader/tests/preprocessors/test_checkcellmetadata.py
nbgrader/tests/preprocessors/test_overwritecells.py

Currently nbgrader may crash if there are cells that aren't nbgrader cells but which have `grade_id` defined in their metadata. This fixes this issue in two places (when the assignment is released, and when it is graded) and adds tests.

Handle grade ids for non-nbgrader cells

---

nbgrader/api.py

If you want to use postgres instead of sqlite, you have to provide a name for enums. This PR adds that.

Add name parameter to enums

---

nbgrader/auth/base.py
nbgrader/auth/hubauth.py
nbgrader/html/formgrade.py
nbgrader/tests/formgrader/base.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/fakeuser.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

When using the formgrader with JupyterHub, you can specify the path to the autograded notebook files. However, this only really allows one grader to be able to access these notebooks. What would be nice is if *any* grader could access the notebook files.
This PR makes it possible by allowing any grader to access the notebook server of a specified "formgrader user". This requires that admin access be enabled in JupyterHub, and that the user whose token the formgrader is using is an admin user. Ideally, the "formgrader user" would *not* be an admin user, and should probably not even be a real account -- it should be a user specifically created for running nbgrader.

Access notebook server of formgrader user

---

flit.ini

Needed for extension installing.
and
closes #338
(it was present in tests because its a flit dependency)

Add `requests` to dependencies.

---

nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/collectapp.py
nbgrader/apps/releaseapp.py
nbgrader/tests/apps/base.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/apps/test_nbgrader_validate.py

This allows an instructor to specify the root course directory in `nbgrader_config.py` so that the commands don't always need to be run from the root of the directory but can be run from anywhere on the system. Closes #383 
In the process I also fixed a bunch of places in the app tests where they were using hardcoded paths rather than `os.path.join`.
cc @jonathanmorgan

Specify root course directory

---

nbgrader/apps/assignapp.py
nbgrader/preprocessors/clearsolutions.py
nbgrader/tests/apps/files/test-no-metadata.ipynb
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/preprocessors/test_clearsolutions.py

Fixes #403
This allows you to run `nbgrader assign --no-metadata` and it will not perform any metadata validation or modify it either. Can be used in conjunction with `--no-db` to just replace solution regions and not use the "Create Assignment" toolbar or save anything into the database.
cc @jklymak

Add --no-metadata option to nbgrader assign

---

.travis.yml
CONTRIBUTING.md
setup.py
tasks.py

This makes it possible to install with `python setup.py develop` regardless of whether you're running python 2 or python 3. It may not always work exactly the same way as it does with setuptools since this uses flit on the backend, but for basic usage it should be consistent, at least.
cc @jklymak

Make a friendlier development install

---

nbgrader/auth/hubauth.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/formgrader/test_auth_failures.py
nbgrader/tests/formgrader/test_gradebook_navigation.py

Ok @jonathanmorgan, I think I finally figured out the https issue!
Flask automatically redirects requests that don't have a trailing slash, e.g. if you access `/hub/nbgrader/example_course`, it will redirect to `/hub/nbgrader/example_course/`. However, for some reason that I can't ascertain, when it does this redirect it will *also* redirect to `http://`, even if the original request was for `https://` and the appropriate header (`X-Forwarded-Proto`) is set in the request.
This PR intercepts all redirect requests and if they should start with `https://` but don't modifies the response to have the correct location. It's kind of a hack, but should work for now. In the 0.3.0 release of nbgrader this is fixed properly because we've switched to using tornado (see #397).
Fixes #400

Redirect flask back to https

---

nbgrader/tests/utils/test_utils.py
nbgrader/utils.py

There is a bug on python 2 where if there is a unicode string in the cell source, then computing the checksum will fail.

Fix UTF-8 encoding bug on python 2

---

CONTRIBUTING.md

Fixes https://github.com/jupyter/nbgrader/issues/420.

Fix Contributor Guide link

---

dev-requirements.txt
docs/requirements.txt
docs/source/contributor_guide/installation_developer.rst
requirements.txt
scripts/nbgrader
setup.py
tasks.py

@ellisonbg asked me to open this PR because the flit based setup.py prohibited him from doing some normal pip operations, see his comment in #409 .  I mostly used the old setup.py that existed before flit was added, however some modifications were required to reflect the new state of nbgrader.
This PR does not remove flit.
closes #428

Reintroduce flit-less setup.py

---

.travis.yml
flit.ini
nbgrader/tests/formgrader/fakeuser.py
nbgrader/tests/formgrader/test_auth_failures.py
nbgrader/tests/formgrader/test_configproxy_auth_failure.py
nbgrader/tests/formgrader/test_formgrader_js.py
nbgrader/tests/formgrader/test_gradebook_navigation.py
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/tests/nbextensions/test_create_assignment.py
requirements.txt
setup.py
tasks.py

This should fix the build errors that are occuring on master currently... the issues were:
1. Related to moving the celltoolbar menu into the View menu in the notebook.
2. Fixing the JupyterHub cookie bug (https://github.com/jupyter/jupyterhub/pull/290) in more recent JupyterHub releases.
3. Making sure JupyterHub is installed on Python 3.5.
4. Removing `os.setpgrp()` from the fake spawner, because it doesn't work on Travis.
This also splits the javascript tests into two separate groups, one for the formgrader and one for the nbextensions, which should hopefully make restarting tests a little less cumbersome.

Fix build errors

---

docs/source/user_guide/03_generating_assignments.ipynb
docs/source/user_guide/04_autograding.ipynb
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/nbextensions/conftest.py

This deprecates the `--create` flags for `nbgrader assign` and `nbgrader autograde` in favor of specifying assignments and students in the `nbgrader_config.py` file. I am leaving in the `--config` option for the time being so that it can print a warning -- it won't work, but it will tell people what they need to do. Fixes #415

Specify assignments and students in the config file

---

nbgrader/apps/baseapp.py
nbgrader/tests/apps/base.py
nbgrader/tests/apps/test_nbgrader_autograde.py

This PR accomplishes two things:
1. It skips failed assignments and only raises an error at the end
2. It logs to file so that errors are more easily recoverable
Fixes #416

Skip failures and log to file

---

README.md
docs/source/user_guide/01_philosophy.rst
docs/source/user_guide/01a_filestructure.rst
docs/source/user_guide/01a_installation.rst
docs/source/user_guide/01a_interface.rst
docs/source/user_guide/02_developing_assignments.rst
docs/source/user_guide/03_generating_assignments.ipynb
docs/source/user_guide/04_autograding.ipynb
docs/source/user_guide/05_manual_grading.rst
docs/source/user_guide/06_returning_feedback.ipynb
docs/source/user_guide/index.rst

This PR addresses issue #392. The user guide will frequently be the first documentation read by those interested in trying out nbgrader. The user guide must explain the project and its use, empower the user to try installing nbgrader, and to guide an instructor toward using nbgrader in a course.
The User Guide table of contents is now broken up into logical subsections of 3-4 items per subsection to improve learning and comprehension for those new to nbgrader. Examples are now titled with the format "Workflow example: Instructor..." or "Workflow example: Student..."
"Philosophy" is modified to be a high level project and benefits overview.
A new section for "Interface highlights" is added to share the user interface gifs that were recently added to the README.
There is a new section …

[WIP] Restructure user guide TOC and doc flow to support new users

---

nbgrader/apps/formgradeapp.py
nbgrader/formgrader/base.py

Prefix all the options in the `settings` dictionary so that they do not conflict with preexisting settings. This is necessary to hook up the formgrader's routes to another application, such as the notebook server.

Update formgrader options to not conflict with the notebook

---

flit.ini
nbgrader/tests/formgrader/manager.py
requirements.txt

Fixes failing tests. Also pins `jupyter_client` to less than 4.2.

Confirm no SSL when running jupyterhub

---

nbgrader/apps/baseapp.py
nbgrader/apps/extensionapp.py
nbgrader/apps/formgradeapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/tests/__init__.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/apps/test_nbgrader_feedback.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/formgrader/test_nbgrader_formgrade.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py

Fixes #463 by having tests create nbgrader apps in the same python session rather than calling out to subprocess. This was a little tricky to do because it involved a lot of monkeypatching of things like sys.stdout, but ultimately I think I have gotten it to work correctly!

Speed up tests

---

flit.ini
requirements.txt

Not meant to merge as-is. This is to verify that jupyter/jupyter_client#141 actually works.
Once that's confirmed and the fix released, I'll update this to just unpin jupyter_client.

unpin jupyter-client

---

nbgrader/formgrader/static/js/models.js

Fixes #462 by changing the default message to:
@willingc @dsblank do you think this is clear enough that it will render in the feedback (given that it doesn't actually render in the formgrader interface)? Or do you think I should also add something indicating specifically that markdown added here will render properly in the feedback?

More helpful default comment box message

---

nbgrader/apps/__init__.py
nbgrader/apps/nbgraderapp.py
nbgrader/apps/quickstartapp.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/installation.rst
nbgrader/tests/apps/test_nbgrader_quickstart.py

Fixes #338 
Ping @willingc -- can you test out this PR and let me know if you think this "quickstart" example works ok?

Create nbgrader quickstart command

---

nbgrader/apps/baseapp.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/test_nbgrader_submit.py

Fixes part of #504 
@lgpage would you mind checking this PR out and testing whether it fixes that test failure for you?

Use .utcnow() rather than .now()

---

nbgrader/tests/__init__.py

Fixes #504 
@lgpage If you run `invoke tests` using this PR do they all pass now? This doesn't actually fix the coverage problem, but should at least not throw an error.

Produce a warning if no coverage files are produced

---

nbgrader/tests/__init__.py
nbgrader/tests/formgrader/manager.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/tests/nbextensions/test_create_assignment.py

Sometimes the subprocesses don't exit cleanly if the test fail, which then makes subsequent tests fail (because the ports aren't available). Also, if there is something else already running on the ports that are expected to be free, the tests will fail. So, this makes the subprocesses run on random ports instead.
Ideally, the subprocesses should always exit cleanly, but that's a separate issue.

Run notebook/formgrader/jupyterhub on random ports during tests

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/formgradeapp.py
nbgrader/apps/quickstartapp.py
nbgrader/tests/apps/test_nbgrader.py
nbgrader/tests/apps/test_nbgrader_quickstart.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/tests/nbextensions/conftest.py

Fix failing windows tests

---

nbgrader/api.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/docs/source/api/models.rst
nbgrader/docs/source/index.rst
nbgrader/docs/source/plugins/index.rst
nbgrader/docs/source/plugins/late-plugin.rst
nbgrader/docs/source/spelling_wordlist.txt
nbgrader/docs/source/user_guide/faq.rst
nbgrader/formgrader/templates/feedback.tpl
nbgrader/plugins/__init__.py
nbgrader/plugins/base.py
nbgrader/plugins/latesubmission.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/getgrades.py
nbgrader/preprocessors/latesubmissions.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Framework for loading plugin functions.
Adds enhancement for #233 
TODO list from the discussions below:

Late penalty plugin

---

conda.recipe/meta.yaml
nbgrader/_version.py
nbgrader/preprocessors/clearsolutions.py
nbgrader/tests/preprocessors/test_clearsolutions.py

Fixes #517
The idea here is that you can specify the code stubs and solution region delimeters for the `ClearSolutions` preprocessor as a dictionary keyed by language, where the language should be the same as the language of the kernelspec in the notebook metadata. This way, nbgrader can flexibly handle assignments with notebooks that have different kernels. For example, the config file might look like:
```python
c = get_config()
c.ClearSolutions.code_stub = {
"python": "# YOUR CODE HERE\nraise NotImplementedError()",
"javascript": "// YOUR CODE HERE\nthrow new Error();"
}
c.ClearSolutions.begin_solution_delimeter = {
"python": "### BEGIN SOLUTION",
"javascript": "// BEGIN SOLUTION"
}
c.ClearSolutions.end_solution_delimeter = {
"python": "### END SOLUTION",
"javascript": "// END SOLUTION" …
```

Allow code stubs to be language specific

---

nbgrader/docs/source/configuration/jupyterhub/nbgrader_config.py
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/grades.csv
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/philosophy.rst

Make it clearer how to set due dates

---

nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/docs/source/user_guide/installation.rst
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb

cc @dsblank @whositwhatnow 
> Are the Assignments list showing up? No, then they might need to edit nbgrader_config.py. I have seen that file: with the wrong name, typos (case, missing quotes).
@dsblank you left this comment in #541. Can you give me a more specific example of what went wrong? Was the class name wrong or something? Do you have the error that it printed out? I'm happy to update this PR with more specifics about this suggestion, I just am not entirely sure what would specifically be most helpful to include.

Document how to install the assignment list extension for all users

---

nbgrader/api.py
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/exportapp.py
nbgrader/apps/formgradeapp.py
nbgrader/docs/source/api/gradebook.rst
nbgrader/docs/source/user_guide/extract_grades.py
nbgrader/preprocessors/getgrades.py
nbgrader/preprocessors/latesubmissions.py
nbgrader/preprocessors/overwritecells.py
nbgrader/preprocessors/saveautogrades.py
nbgrader/preprocessors/savecells.py
nbgrader/tests/api/test_gradebook.py
nbgrader/tests/api/test_models.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/preprocessors/test_getgrades.py
nbgrader/tests/preprocessors/test_overwritecells.py
nbgrader/tests/preprocessors/test_saveautogrades.py
nbgrader/tests/preprocessors/test_savecells.py

Fixes #560 
This adds a `close()` method to the `Gradebook` object and modifies everything to use that rather than `Gradebook.db.close()`. This ensures that the engine is also shutdown properly.

Close db engine

---

nbgrader/apps/baseapp.py
nbgrader/apps/fetchapp.py
nbgrader/apps/listapp.py
nbgrader/apps/submitapp.py
nbgrader/nbextensions/assignment_list/handlers.py
nbgrader/nbextensions/static/assignment_list/assignment_list.js
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_submit.py

This adds a new option, `path_includes_course`, to the TransferApps so that they work a little better with multiple courses. If this option is set to True, then `nbgrader fetch` will fetch assignments to `<course_id>/<assignment_id>` (rather than just to `<assignment_id>`). Similarly, if the option is set to True, then `nbgrader submit` will look for assignments at `<course_id>/<assignment_id>`. I have also made sure that this functionality works from the assignment list extension.
This fixes #554 though it doesn't fully address the full issue with multiple courses yet (i.e. #544). I am going to try to address that fully in a separate PR, this is just a first step.
cc @dsblank

Add better support to transfer apps for multiple courses

---

nbgrader/apps/fetchapp.py
nbgrader/tests/apps/test_nbgrader_fetch.py

This should make it easier for students to overwrite a single notebook if they need to, rather than having to blow away the entire problem set.

Add option to nbgrader fetch for replacing missing files

---

nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/preprocessors/execute.py
nbgrader/tests/apps/files/infinite-loop-with-output.ipynb
nbgrader/tests/apps/files/infinite-loop.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py

cc @ddbourgin
This fixes a bug in handling failures during autograding (if one student's assignment failed, then the whole thing would break, even though it should not). It also prints out a more informative message if the kernel becomes unresponsive.

Handle autograding failures better

---

CONTRIBUTING.md
README.md
nbgrader/apps/quickstartapp.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/user_guide/advanced.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

nbgrader/apps/notebookapp.py
nbgrader/tests/nbextensions/conftest.py

Turns out it is actually easy to disable token auth for the nbextension tests and for the FormgradeNotebookApp.
It will be a bit more work if you actually want to use token auth for the FormgradeNotebookApp.
Closes #582

Changes for Notebook v4.3 tests

---

nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Add catches for empty timestamp files and invalid timestamp strings

---

nbgrader/docs/source/spelling_wordlist.txt

It seems `nbconvert` was updated to v5.0 and released perfectly between my PR's and merge, causing the docs builds to fail on master.

`basename` to wordslist

---

nbgrader/tests/apps/test_nbgrader_autograde.py

Sorry @jhamrick, some how I forgot to commit this with #585.
This is a small test update to check both empty `timestamp.txt` files and **invalid timestamp strings in the `timestamp.txt` file**

Test empty and invalid timestamp strings

---

conda.recipe/meta.yaml
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/validateapp.py
nbgrader/docs/source/contributor_guide/metadata.rst
nbgrader/docs/source/index.rst
nbgrader/nbformat/__init__.py
nbgrader/nbformat/common.py
nbgrader/nbformat/v1.json
nbgrader/nbformat/v1.py
nbgrader/preprocessors/checkcellmetadata.py
nbgrader/preprocessors/headerfooter.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/preprocessors/base.py
nbgrader/tests/preprocessors/test_checkcellmetadata.py
setup.py

Fixes #478
This adds in a schema for the nbgrader metadata, and validates it in a number of places. There is no validation of the metadata currently in the create assignment extension, but I think that is going to be fairly complicated to implement so I'm saving it for a future PR.

Add metadata schema and documentation

---

nbgrader/apps/formgradeapp.py
nbgrader/auth/hubauth.py
nbgrader/auth/noauth.py

Fixes #472
This prints a more useful error message:
```
$ nbgrader formgrade
[FormgradeApp | INFO] Serving MathJax from /Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/site-packages/notebook/static/components/MathJax/MathJax.js
[FormgradeApp | ERROR] Address already in use by another process: http://localhost:5000
[FormgradeApp | ERROR] Try running nbgrader with a different port, e.g. nbgrader formgrade --port=5001
```
and also is more explicit about where the formgrader is running:
```
$ nbgrader formgrade --port=5001
[FormgradeApp | INFO] Serving MathJax from /Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/site-packages/notebook/static/components/MathJax/MathJax.js
[FormgradeApp | INFO] Notebook server is running at http://localhost:55550/notebooks/
[FormgradeApp | INFO] …
```

Clarify formgrader port and suppress notebook output

---

nbgrader/preprocessors/clearsolutions.py
nbgrader/tests/preprocessors/test_clearsolutions.py

Fixes #551 and fixes #422 
I didn't explicitly include fuzzy string checking for #422 but that's because the delimeters are actually pretty close, so this is difficult to do -- for example, "BEGIN SOLUTION" and "END SOLUTION" actually share a large amount of text because of the "SOLUTION" part. But, I think being able to be flexible about everything else (e.g. comment marks) will still be sufficient for that.
cc @dsblank

Don't be as strict about solution delimeters

---

dev-requirements-windows.txt
dev-requirements.txt
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/contributor_guide/installation_developer.rst
tasks.py

Fixes #599 (I think)
@lgpage if you could see if this helps on conda forge that would be great -- I *think* the issue really is just spurious test cases so I added in a pytest plugin that will rerun failed tests. This fixed the test failures at least on the Jenkins build server, so I'm hoping it will on appveyor too.
(There are a few other changes in this PR that address issues I was having with getting the tests to run on Jenkins, but the main thing is adding the `pytest-rerunfailures` to the dev requirements and then adding `--rerun=1` to the pytest command).

Fix Windows tests

---

nbgrader/tests/apps/test_nbgrader.py

On the conda forge linux image the stupid `'import sitecustomize' failed` error pops up which causes the `test_check_version` test to fail, eg: https://circleci.com/gh/lgpage/staged-recipes/48
This PR updated the test to only check the last line output, I.e. only checks the `nbgrader` version info and not anything else.

Don't fail `test_check_version` test on `'import sitecustomize' failed error`

---

nbgrader/api.py
nbgrader/apps/dbapp.py
nbgrader/tests/apps/test_nbgrader_db.py

Add and use a Gradebook contextmanager for DbApp and DbApp tests

---

nbgrader/preprocessors/execute.py
nbgrader/tests/formgrader/conftest.py
nbgrader/tests/nbextensions/conftest.py
tasks.py

This is an interim effort to deal with the IOPub timeouts we're getting in the windows tests, until https://github.com/jupyter/nbconvert/pull/513 is merged and released. Not sure if this will actually help all that much, but let's see!
cf #644 
cc @lgpage

Bump the number of test reruns even higher

---

nbgrader/nbextensions/assignment_list/assignment_list.js

The base-url is not expected to be encoded in the server-side jupyter web handlers, so certain character (e.g., @)  were causing 404s due to mismatch between the nbextension URLs and the server extension API URLs.
You can see an example of how this is dealt with in the jupyter project [here](https://github.com/jupyter/jupyter_server/blob/dd4b052403cc0ce70dbde9bfc6c71d6b09e814ec/notebook/static/services/config.js#L26) and [here](https://github.com/jupyter/jupyter_server/blob/dd4b052403cc0ce70dbde9bfc6c71d6b09e814ec/notebook/static/services/contents.js#L45).
This is an issue because in my JupyterHub deployment, usernames are email addresses which contain `@`, which becomes `%40` when encoded. This means the URLs for the AJAX calls are invalid.
I left the URI encoding of the file paths, as …

Preventing URI Encoding of the base-url in the assignment_list extension

---

nbgrader/auth/hubauth.py

JUPYTERHUB_SERVICE_PREFIX has the form JUPYTERHUB_BASE_URL/services/:service-name
it includes the application's base URL already, so don't append it twice
closes #677

JUPYTERHUB_SERVICE_PREFIX is already the full URL prefix

---

nbgrader/tests/apps/test_nbgrader.py

Just in case it is somehow finding another version of nbgrader...

Use sys.executable when executing nbgrader

---

nbgrader/api.py
nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/dbapp.py
nbgrader/apps/exportapp.py
nbgrader/docs/source/user_guide/extract_grades.py
nbgrader/docs/source/user_guide/faq.rst
nbgrader/preprocessors/getgrades.py
nbgrader/preprocessors/latesubmissions.py
nbgrader/preprocessors/overwritecells.py
nbgrader/preprocessors/saveautogrades.py
nbgrader/preprocessors/savecells.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_db.py

Turn the gradebook into a context manager

---

nbgrader/tests/nbextensions/conftest.py

See https://github.com/SeleniumHQ/selenium/issues/767
This gave me grief while messing around with ``nbextension`` tests, managed to freeze up my PC after running out of memory.

Force phantomjs service to terminate in Linux

---

nbgrader/tests/nbextensions/conftest.py

rather than Popen, which just launches the program.
check_call adds:
- wait for it to finish
- raise error on nonzero exit code
should close #694, if slow extension enabling was indeed the culprit.

use check_call for extension installation in tests

---

nbgrader/tests/nbextensions/test_assignment_list.py

This should fix test failures like this, where it fails the first time and then the rerun fails because the nbgrader command has already been run: https://travis-ci.org/jupyter/nbgrader/jobs/199697338

Force rerun nbgrader commands

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/collectapp.py
nbgrader/apps/dbapp.py
nbgrader/apps/exportapp.py
nbgrader/apps/feedbackapp.py
nbgrader/apps/fetchapp.py
nbgrader/apps/listapp.py
nbgrader/apps/releaseapp.py
nbgrader/apps/submitapp.py
nbgrader/apps/zipcollectapp.py
nbgrader/coursedir.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/server_extensions/formgrader/formgrader.py
nbgrader/tests/apps/conftest.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/nbextensions/test_assignment_list.py

#705 will require quite a bit of refactoring in order to separate the config options from the apps that rely on them. This PR is a first step in that direction. This makes a `CourseDirectory` object that manages the actual directory containing the source files. It's a relatively sparse object at the moment except for its config options, but I am hoping to move more functionality (e.g. stuff from the nbconvert apps) into it in the future.
I will wait to merge this I think until after #526

Move some config options into a CourseDirectory object.

---

nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/collectapp.py
nbgrader/apps/fetchapp.py
nbgrader/apps/listapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/apps/quickstartapp.py
nbgrader/apps/releaseapp.py
nbgrader/apps/submitapp.py
nbgrader/coursedir.py
nbgrader/docs/source/user_guide/faq.rst
nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/exchange.py
nbgrader/exchange/__init__.py
nbgrader/exchange/collect.py
nbgrader/exchange/exchange.py
nbgrader/exchange/fetch.py
nbgrader/exchange/list.py
nbgrader/exchange/release.py
nbgrader/exchange/submit.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_fetch.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_release.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_assignment_list.py

This is the second step after #711 towards addressing #705 
This moves the functionality from applications based on `TransferApp` to standalone objects that inherit from a class called `Exchange`. I have deprecated `TransferApp` entirely, though the other apps (e.g. `FetchApp`) still exist and now inherit directly from `NbGrader`. This shouldn't change the functionality of the exchange apps at all, except for renaming the config options. In general, the config options get renamed as follows:
* `TransferApp` --> `Exchange`
* `ReleaseApp` --> `ExchangeRelease`
* `FetchApp` --> `ExchangeFetch`
* `SubmitApp` --> `ExchangeSubmit`
* `CollectApp` --> `ExchangeCollect`
* `ListApp` --> `ExchangeList`
Still need to make sure all the docs etc. are updated.

Move exchange functionality into non-application classes

---

.travis.yml
appveyor.yml
nbgrader/exchange/exchange.py

This sets the timestamp format for submissions to include microseconds, and also removes python 3.4 test cases. Should make the tests more robust.

Fix nbextension tests

---

nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/formgrader.py

Fixes #741 
This will still create an empty gradebook in the directory if the notebook is run if there is no `nbgrader_config.py` file to specify where the gradebook should be. However, this file will now not be created until the formgrader itself is actually accessed.
cc @Szepi @lgpage

Don't create the gradebook database until formgrader is accessed

---

nbgrader/nbextensions/create_assignment/main.js
nbgrader/tests/nbextensions/test_create_assignment.py

Fixes #684 by setting cell ids by default to `cell-xxxxxxxxxxxxxxxx` where `xxxxxxxxxxxxxxxx` is a random hex string of length 16.
cc @ellisonbg

Set random cell ids

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/apps/baseapp.py
nbgrader/apps/feedbackapp.py
nbgrader/tests/apps/test_nbgrader_feedback.py

I am not sure if this totally fixes #570 but I think it does. In particular, this removes uses of `self.fail` in the nbconvert-based apps and throws an error instead. This is important because the nbconvert apps will catch the error and then cleanup, but if `self.fail` is used, the program terminates immediately.

Better cleanup when nbconvert-based apps crash

---

nbgrader/tests/nbextensions/test_formgrader.py

The formgrader tests keep failing on travis for some reason, and then they get rerun, but then they encounter a different error because they modify state, which means we can't see what the real error is. This PR should at least makes the tests more re-runnable by splitting some of the tests up, so I can track down what's really going on.

Fix inaccurate nbextension test failures after reruns

---

nbgrader/apps/api.py

Fixes #785 
With 1126 submissions, before autograding:
```
--
api.get_autograded_students('ps1')
0.054342s, best of 3
--
api.get_submitted_students('ps1')
0.04315s, best of 3
--
api.get_submissions('ps1')
0.558401s, best of 3
--
gb.submission_dicts('ps1')
0.014699s, best of 3
--
api.get_notebook_submissions('ps1', 'problem1')
0.011708s, best of 3
--
api.get_students()
0.072811s, best of 3
```
after autograding:
```
--
api.get_autograded_students('ps1')
0.926902s, best of 3
--
api.get_submitted_students('ps1')
0.051649s, best of 3
--
api.get_submissions('ps1')
1.04687s, best of 3
--
gb.submission_dicts('ps1')
0.28924s, best of 3
--
api.get_notebook_submissions('ps1', 'problem1')
2.141678s, best of 3
--
api.get_students()
0.25908s, best of 3
```
@lgpage would you mind testing this and see …

Fix slow API calls

---

nbgrader/tests/nbextensions/test_formgrader.py

#788 apparently didn't go far enough...

Fix more inaccurate nbextension test failures after reruns

---

nbgrader/apps/baseapp.py
nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/formgrader.py
nbgrader/server_extensions/formgrader/handlers.py
nbgrader/server_extensions/formgrader/static/js/manage_assignments.js
nbgrader/server_extensions/formgrader/templates/manage_assignments.tpl

If the notebook is started in a different directory than the course directory, the links to the `source` and `release` folders are currently incorrect. This fixes that.

Make sure relative paths to source and release dirs are correct

---

nbgrader/apps/api.py
nbgrader/nbextensions/assignment_list/main.js

Fixes #820
This does two things:
1. Does not attempt to load the assignments in the assignment list until it's actually accessed.
2. Tries to use the exchange in the formgrader, and if it fails, sets the course id to none.

Avoid extension errors when exchange is missing

---

nbgrader/apps/api.py
nbgrader/server_extensions/formgrader/handlers.py
nbgrader/server_extensions/formgrader/templates/manage_assignments.tpl

This will add warnings if the exchange isn't available. This can happen if any of the following are true:
* The OS is windows
* The exchange can't be created
* The course_id isn't set in nbgrader_config.py

Produce warnings if the exchange isn't set up correctly

---

nbgrader/server_extensions/formgrader/formgrader.py

Fixes #855 
Ping @mpacer -- it was in fact this line causing the issue! I needed to change the url to be relative to the notebook directory, rather than the current directory (which defaults to the user's home directory).

Set nbgrader url prefix to be relative to notebook_dir

---

nbgrader/apps/api.py
nbgrader/server_extensions/formgrader/static/js/manage_assignments.js
nbgrader/tests/apps/test_api.py
nbgrader/utils.py

**Before this patch**
Currently, the user may specify, e.g.
```
c = get_config()
c.NbGraderAPI.timezone = 'America/Sao_Paulo' 
```
Then it would correctly convert all timestamps to `'America/Sao_Paulo'`. However, it would also be displayed in the formgrader when the user sets the assignment's due date:
When the user sends this form, the timezone string is concatenated to the time and passed to `utils.parse_utc`, which cannot handle this string format.
**After this patch**
This patch converts `NbGraderAPI.timezone` to a format readable by `parse_utc` before displaying it to the user in the formgrader. This way the user does not need to change the default value presented in the Timezone field: it will just use the configured timezone out-of-the-box.
**Note**
The `dateutil.tz.gettz` function …

Fix NbGraderAPI.timezone handling

---

nbgrader/api.py
nbgrader/tests/api/test_gradebook.py

Fixes #857 
This fixes the issue with students not being displayed in the formgrader. The underlying issue was that `Gradebook.student_dicts()` was returning an empty list, even though the students did in fact exist in the database. This is a edgecase that only seems to occur when there are assignments in the database, but they have a combined zero points. A workaround for the issue is to make sure there is at least one assignment with nonzero points.
cc @jcsutherland

Fix issue with student dictionaries when assignments have zero points

---

dev-requirements-windows.txt
dev-requirements.txt
nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/release/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/submitted/bitdiddle/ps1/problem1.ipynb
tasks.py

Use nbval to test documentation notebooks. Tests are not run on Windows, as at least one example notebook requires a linux filesystem.
Part of sprints at EuroSciPy 2017.

Add nbval for non-Windows tests/CI

---

nbgrader/docs/source/user_guide/installation.rst

Very small tweak. Two code blocks had single colon: not a double:: so were not rendering as a code blocks.

Format code blocks in installation instructions

---

nbgrader/coursedir.py
nbgrader/server_extensions/formgrader/static/js/manage_assignments.js
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/nbextensions/test_formgrader.py

This both checks that assignment ids do not contain '+' when validating the traitlet value for assignment_id, and also prevents assignments with '+' from being created in the formgrader interface.
Fixes #928

Prevent assignments from being created with invalid names

---

nbgrader/converters/autograde.py
nbgrader/tests/apps/test_nbgrader_autograde.py

Fixes #940 by adding a configuration option that allows you to exclude certain files from being overwritten by the source version during autograding. The way you would do this would be like so in `nbgrader_config.py`:
```
c = get_config()
c.Autograde.exclude_overwriting = {"ps1": ["file_to_exclude.py"]}
```
cc @yangkky

Exclude certain assignment files from being overwritten during autograding

---

.travis.yml
appveyor.yml
nbgrader/docs/source/contributor_guide/installation_developer.rst
nbgrader/server_extensions/formgrader/static/js/formgrade.js
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/formgrade_utils.py
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/tests/nbextensions/test_create_assignment.py
nbgrader/tests/nbextensions/test_formgrader.py
nbgrader/tests/nbextensions/test_validate_assignment.py

Fixes #935
Note that unfortunately, the Firefox webdriver does not support capturing logs from javascript. This is annoying, but not a dealbreaker.
In making this change I uncovered a bunch of race conditions in the javascript tests, which is good I guess!

Switch from PhamtomJS to Firefox

---

.travis.yml
tasks.py

Apparently something changed with invoke so that it no longer recognizes tasks with underscores in their names.

Remove underscores from task names

---

nbgrader/server_extensions/formgrader/templates/formgrade.tpl

Currently, LaTeX oversets are rendered weird in the [formgrader](https://homepages.upb.de/jbobolz/nbgraderRenderExample/badRender.html) (i.e. while grading a submission), to the point where some submissions become unreadable. 
In the notebook and the [feedback](https://homepages.upb.de/jbobolz/nbgraderRenderExample/feedback.html), everything is rendered fine.
An example notebook to reproduce the problem can be found [here](https://homepages.upb.de/jbobolz/nbgraderRenderExample/formattest.ipynb)
This pull request changes the way mathjax is included on formgrader pages to be consistent with the include on the feedback page (where everything works fine). It also makes sense to me that the formatting should be the same for the formgrader and the feedback.
I have this change running …

Use mathjax macro for formgrader

---

nbgrader/docs/source/user_guide/autograding_resources.rst

Suggestion for example section on mocking, responding to @jhamrick on the jupyter-education mailing list (autograding output of print statements).
Greetings,
Olav

Include section on mocking (autograding resources)

---

nbgrader/docs/source/contributor_guide/installation_developer.rst

Make changes as required at https://github.com/jupyter/nbgrader/issues/862

Update developer installation instructions

---

README.md
nbgrader/apps/quickstartapp.py
nbgrader/docs/make.bat
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/contributor_guide/installation_developer.rst
nbgrader/docs/source/index.rst
nbgrader/plugins/zipcollect.py

This should cover all #1015 testcases

Fix all redirection

---

nbgrader/docs/source/user_guide/installation.rst

One of the links in the installation file was replaced correctly, but a `>` was omitted. This broke the display of the URL. This PR fixes that typo.

Add missing close > for url to display correctly

---

nbgrader/exchange/collect.py
nbgrader/exchange/submit.py

- Previously, the exchange was writeable by all users, readable by all
users, but only listable by the instructors.  Non-guessability of
the filename is the method of security.  However, filenames are a
function of (username, assignment_id, and microsecond timestamp).  A
microsecond timestamp alone is not immediately guessable, but not
perfect either.
- This patch introduces a random string to the submission filename.
- This is backwards compatible, except if there is a "+" in a username
and the instructor uses new nbgrader and students submit with old
nbgrader.  This is because "+" is used to split the path components,
but is also a valid character for usernames.  It was split with
.rsplit("+", 2) before, now it is .rsplit("+", 3).
- Related: #978
- Closes: #978
---
The non-extension …

Add random string to submission filenames for better hiding

---

nbgrader/tests/apps/files/data.txt
nbgrader/tests/apps/files/open_relative_file.ipynb
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/validator.py

- This was fixed in #880, but a refactoring to split reading from
preprocessing has removed the wrapper around the preprocess step.
There is in fact a test for this, but perhaps pytest chdirs to the ipynb's directory so that the test can't fail.
I'm still making my final tests but this seems to work.

Change to notebook directory when validating (repeat of #880)

---

nbgrader/docs/source/user_guide/faq.rst

Added an entry to the FAQ that covers the common timeout errors for autograding/validation that takes too long, including a quick fix.
Fixes #931

Documentation fix to add info re: timeout errors.

---

dev-requirements-windows.txt
nbgrader/docs/source/spelling_wordlist.txt

I don't know whether this PR should go to 'master' or '0.5.x'. Should Travis tests be made to regard spelling errors as errors? (It appears that you have to check the logs to see if any errors are identified.)

Dev requirements and spelling tests

---

paper/paper.bib

Capitalization fixes and add missing DOI.
Does the JupyterHub reference have a URL or DOI?
Cc: https://github.com/openjournals/jose-reviews/issues/32

JOSE paper bib updates

---

paper/paper.md

This makes the capitalization of "Jupyter Notebook" more consistent, as per https://github.com/openjournals/jose-reviews/issues/32#issuecomment-450084190 .
Can one of @willingc @dsblank @lgpage @ellisonbg take a second look just to make sure I didn't make a typo somewhere?
cc @jedbrown

Ensure consistency in capitalizing Jupyter Notebook

---

nbgrader/utils.py
nbgrader/validator.py

- This allows a notebook to know when it is validating and when it is
not.
- This was needed for a course with using major computational
resources in each notebook.  The notebook is tell it is validating
and go into a validation mode, using only cached data.
====
This came up as a need recently.  Actual use case is training models in the notebook and saving the models to a file, the validation can't re-do that because it takes so long.  For autograding, we can use hidden tests to change behavior, but I didn't find a way to do this when validating.
- Is there a proper way to do this, so that this change isn't needed?
- Untested.  If this is considered useful, I might be able to figure out tests myself.
- making a new context managed seems heavy-handed compared to the minimum change needed. …

Set env var NBGRADER_VALIDATING when validating

---

nbgrader/validator.py

An instructor asked why the "validate" interface didn't present errors in all cells (instead of just those that were graded).  It seems it was designed this way.
We took a look and figured out how to make it validate everything: we added a `validate_all` option, which makes the validation interface show all errors.  There's no difference in what's actually computed, it just doesn't hide the errors from non-graded cells.
This is currently without tests, though we've been using it for some time.  I can look at tests if the reception is positive.

Validate all cells

---

nbgrader/api.py

The present version of `nbgrader` is incompatible with `SQLAlchemy 1.3+` as pointed out in #1073. The reason is that version 1.3+ requires to explicitly specify the left side of a join (https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#query-join-handles-ambiguity-in-deciding-the-left-side-more-explicitly). This PR proposes a solution by introducing the appropriate `select_from` method before a `join`.

compatibility with SQLAlchemy 1.3+

---

nbgrader/validator.py

Root problem: it seems that validation timeout could not be changed with `--ExecutePreprocessor.timeout`, and in fact nothing we did would adjust the validation timeout.
=====
Commit message:
- We found that preprossor config was not followed - in particular,
the ExecutePreprocessor.timeout wasn't noticed when it was increased
to 120.
- A instructor did some digging and suggested that this change would
make the configuration work.
- I don't know what the root problem could be, and I don't know if
this is even needed.  Is this patch useful, or is there a "right"
way of making traitlets work?
=====
So I don't know if this patch is needed.  I don't know if it's the right way.  From what I can tell about Traitlets, this shouldn't be needed.  Also documentation says that …

Give ExecutePreprocessor the Traitlets config during validation

---

nbgrader/api.py
nbgrader/apps/api.py
nbgrader/apps/dbapp.py
nbgrader/exchange/exchange.py
nbgrader/exchange/fetch.py
nbgrader/exchange/list.py
nbgrader/exchange/submit.py
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/utils.py

This is a more finalised version of #893 with [permission](https://github.com/zonca/nbgrader/pull/1) from zonca to post this with his code here as a new PR. 
* Only api_tokens made for users in the admin_users list will work.
* You must generate an `'api_token'` with with the command `jupyterhub token <some admin user>`. The default api token that is created even if the user that you are using nbgrader in is in the admin_users list does not work, so generate it manually with that command wherever your jupyterhub.sqlite file cd nbis.
* For teachers/TA's have `'formgrade-<course-id>'` as the name of your group. 
* For the students have `'nbgrader-<course-id>'` as the name, you can also ommit this because it is made for you when adding a student if they are not already in Jupyterhub config …

Restrict access for students to different courses

---

nbgrader/apps/submitapp.py
nbgrader/coursedir.py
nbgrader/exchange/submit.py
nbgrader/tests/apps/test_nbgrader_submit.py

This implements `nbgrader submit ps1 --student a4.jane.doo`
Some use cases:
- handling groups of students: helping the instructors access just the students of their group by adding a common prefix
- submissions directly from a jupyterhub, where all students share the same jovian login; in general infrastructures where all students share the same login
- a posteriori submissions by the instructor (e.g. because they are collected by some other mean)

Customizable student ID in `nbgrader submit`

---

dev-requirements.txt
tasks.py

`python tasks.py tests --group=python` will add the `--numprocesses=auto` flag,
which will start one test runner per available CPU core.

Run test in the `python` group in parallel using pytest-xdist

---

nbgrader/tests/apps/conftest.py

This made a big difference when debugging tests. Perhaps it would help others?

naming the temporary directories in tests

---

nbgrader/apps/updateapp.py
nbgrader/apps/validateapp.py
nbgrader/converters/base.py
nbgrader/nbgraderformat/__init__.py
nbgrader/nbgraderformat/common.py
nbgrader/nbgraderformat/v1.py
nbgrader/nbgraderformat/v2.py
nbgrader/nbgraderformat/v3.py
nbgrader/server_extensions/validate_assignment/handlers.py
nbgrader/tests/apps/files/too-new.ipynb
nbgrader/tests/apps/test_nbgrader_update.py
nbgrader/tests/nbgraderformat/test_v2.py
nbgrader/tests/nbgraderformat/test_v3.py

Fixes #916
I actually already had functionality for stripping extra keys, but there was a bug in how it was implemented so it wasn't actually getting trigger properly. This fixes that issue, and also clarifies if the schema version is too new (which came up in #1086)

Remove extra keys in nbgrader metadata and better schema mismatch errors

---

nbgrader/coursedir.py
nbgrader/exchange/exchange.py
nbgrader/tests/apps/test_nbgrader_submit.py
nbgrader/tests/utils/test_utils.py
nbgrader/utils.py

- ignore too large files
- ignore non explicitly included files
Resolves #874.

Extended support for filtering files copied in the exchange

---

nbgrader/apps/baseapp.py
nbgrader/apps/generateconfigapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/tests/apps/test_nbgrader_generate_config.py

The generate_config subcommand uses its own `.classes` attribute to find the classes to expose in the config file. So it needs to look up the whole list like NbgraderApp does (for `--help-all`). This PR adds it as a new method on the base class, and makes both applications call that.
Closes gh-1089

Locate all configurable classes for generate_config subcommand

---

nbgrader/tests/apps/conftest.py

This fixes a typo from pull request #1109.

Fix typo in tmp filename prefix in conftest.py

---

nbgrader/apps/assignapp.py
nbgrader/apps/autogradeapp.py
nbgrader/converters/assign.py
nbgrader/converters/autograde.py
nbgrader/docs/source/user_guide/creating_and_grading_assignments.ipynb
nbgrader/tests/apps/test_api.py
nbgrader/tests/apps/test_nbgrader_assign.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_db.py

In a demo yesterday, @jhamrick suggested that the `nbgrader autograde` should behave as though `--create` was specified by default. This implements that change.
The `--create` flag can still be passed, to allow for scripts written with it, but it's a no-op now. You can still access the old behaviour (error if student doesn't exist in the database) by passing `--Autograde.create_student=False`.
**Edit:** The same now also applies to `nbgrader assign` - `--create` is now the default.

Autograde & Assign: create missing students/assignments by default

---

nbgrader/__init__.py
nbgrader/auth/jupyterhub.py
nbgrader/docs/source/user_guide/installation.rst
nbgrader/nbextensions/course_list/course_list.css
nbgrader/nbextensions/course_list/course_list.js
nbgrader/nbextensions/course_list/main.js
nbgrader/server_extensions/course_list/__init__.py
nbgrader/server_extensions/course_list/handlers.py
nbgrader/server_extensions/formgrader/apihandlers.py
nbgrader/tests/apps/test_nbgrader_extension.py
nbgrader/tests/nbextensions/conftest.py
nbgrader/tests/nbextensions/test_course_list.py

Fixes #1060 and related to #1030
This creates a new extension called `course_list` that displays all courses available to an instructor, including local ones (that are loaded into the same single user notebook) and JupyterHub ones (which are found by querying the JupyterHub services). Currently it looks something like this:
@damianavila @BertR @sigurdurb

Add a course list extension that shows all courses an instructor can manage

---

nbgrader/server_extensions/course_list/handlers.py

I broke the `multiple-classes-dev` branch when I merged #1113. This fixes that.

Fix incorrect usage of Exchange.course_id

---

.travis.yml

Will speed up running the tests a bit further too.

Only run nbextensions tests on oldest and newest versions of python

---

nbgrader/apps/baseapp.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/tests/apps/test_nbgrader.py

Fixes #997
This makes it so that setting the logfile has an effect, and also makes the default not to log to file. I think this makes more sense, as the logfile is not so useful unless you're running in a cloud setup anyways. I have added some documentation to the JupyterHub docs to encourage people to set the logfile when they're using nbgrader with JupyterHub.

Fix logfile

---

nbgrader/exchange/exchange.py
nbgrader/exchange/fetch.py
nbgrader/server_extensions/assignment_list/handlers.py

Currently, nbgrader assumes that fetching assignments via the web UI will always put them in `notebook_dir` - so that `notebook_dir`/`default_url` can't be used.  This PR seem to minimally fix that - at least I could do one manual test and it worked.  It will need serious examination from others, in addition to tests and documentation.
Please let me know what you think: is this on the right track?  What should be done to make it useful?
---
I'm not sure if the `.tag(config=True)` is needed.
The current config needs `c.Exchange.assignment_dir = "/notebooks/` in `nbgrader_config.py` and `c.AssignmentList.assignment_dir` in `jupyter_notebook_config.py`.

Allow setting a different assignment dir for students than the root notebook directory

---

nbgrader/docs/source/user_guide/advanced.rst

This PR proposes to add to the advanced topics section of the docs a section on grading in a docker container with the help of ``envkernel``. The idea was to concentrate on docker as discussed in #483. Singularity is mentioned as a possibility at the end. I also did not follow the ``envkernel`` README very closely but refer to the README in a couple of places instead. 
Any suggestions for improvements are very welcome.
Closes #483

section on grading in docker container

---

nbgrader/coursedir.py
nbgrader/tests/apps/test_nbgrader_assign.py

Fixes #1008
This standardizes the path to the course directory root so that it is an absolute path, and adds a test to be sure that the trailing slashes are indeed removed.

Ensure course directory root path has no trailing slashes

---

nbgrader/docs/source/configuration/jupyterhub_config.rst

Documentation on how to setup Multiple classes with No authentication, Jupyterhub authentication and Custom authentication.
Revisions welcome.
@jhamrick @BertR @damianavila

Documentation for multiple classes

---

nbgrader/exchange/collect.py
nbgrader/tests/apps/test_nbgrader_collect.py

Optional consistency check between owner and student_id upon collect

---

nbgrader/alembic/versions/167914646830_added_task_cells.py
nbgrader/tests/apps/test_nbgrader_db.py

There was a bug in the tests for upgrading the database in which they were succeeding, but this is because when `nbgrader assign` was run in the test case, it created the required database tables. This adds a test which does not first run `nbgrader assign` to account for this issue, and fixes the alembic scripts so that the test succeeds.

Add test to ensure that db upgrade succeeds before running assign

---

nbgrader/converters/base.py
nbgrader/converters/generate_assignment.py
nbgrader/converters/generate_feedback.py
nbgrader/coursedir.py
nbgrader/exchange/exchange.py
nbgrader/exchange/release_assignment.py
nbgrader/exchange/release_feedback.py
nbgrader/tests/apps/base.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_collect.py
nbgrader/tests/apps/test_nbgrader_generate_assignment.py
nbgrader/tests/apps/test_nbgrader_generate_feedback.py
nbgrader/tests/apps/test_nbgrader_releaseassignment.py
nbgrader/tests/apps/test_nbgrader_releasefeedback.py

Hi,
I have been working on a setup where I wanted instructors to be able to share releasing files, collecting, and so on.nbgrader says that it doesn't support this, but I tried anyway.  This PR contains the changes needed to make this work, which have been mostly minimal.  Things are not perfect, and some of these changes may be not needed.  I'm still testing locally and this is mainly to get some more expert opinions.
This adds a new option `groupshared` which enables the behavior.  By default, no behavior should change.
These changes assume that the following are set by the environment (admins).  They are satisfied in my setup because we run via kubespawner and I carefully control these:
- instructors have a unique-per-course primary gid which students do not have.  Alternatively, the …

Allow instructors to share files via shared group id

---

nbgrader/exchange/fetch_feedback.py
nbgrader/exchange/list.py
nbgrader/exchange/submit.py

This adds assignment_dir config to several places it was missing (see #1001).
Incidentally, while testing this I noticed something.  Without this, you have to be in the notebook root directory to fetch/submit/etc.  With this, you can be in any directory.  That seems to imply it would be beneficial to set the default to abspath(Jupyter notebook_dir) (but we can't use that directly, because it still needs to be configurable separately, that's the point of #1001).

assignment_dir: Add into several missing places

---

nbgrader/nbextensions/assignment_list/assignment_list.js
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/server_extensions/formgrader/apihandlers.py

- I was basically operating by guessing, so someone should check if
this is appropriate - there's quite a difference between the way
that assignment_list and formgrader access the API.  I copied from
the "fetch" is assignment_list and adjusted ExchangeFetchAssignment
to ExchangeFetchFeedback
- Also there's a bit too much copy-and-paste, but fixing that is
beyond me...
- But I did just run this and it *seems* to work... as in it can
fetch.
- Closes: #1181

Move the fetch feedback API from formgrader to assignment_list

---

nbgrader/converters/base.py
nbgrader/coursedir.py
nbgrader/exchange/release_feedback.py
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_generate_feedback.py
nbgrader/tests/apps/test_nbgrader_releasefeedback.py

This adds a `--CourseDirectory.student_id_exclude` which can exclude the given students from autograding and other tasks, as in #1157.  This is useful if there is a bug which causes autograding to halt if there is a problem with one particular student.
There are no tests yet and I haven't used much.  I'm not sure if I found the right place to add this.  If it is, then let me know and I'll see about adding the tests and documentation.
-----
- This is the counterpart of the CourseDir.student_id option in that
it rejects single students, defaulting to them all.  Really, first
student_id is applied, and then student_id_exclude ones are skipped.
- This is useful if a single student is erroring and needs to be left
out.

Add CourseDir.student_id_exclude option to exclude students

---

nbgrader/auth/jupyterhub.py
nbgrader/docs/source/configuration/jupyterhub_config.rst
nbgrader/docs/source/contributor_guide/releasing.rst
nbgrader/exchange/list.py
nbgrader/server_extensions/course_list/handlers.py

If just running a single class on JupyterHub and not using JupyterHub auth, it should still be possible to access the formgrader from the courses list. This makes this possible, and also clarifies some of the documentation around setting this up.
Closes: #1189

Allow access to formgrader when not using JuptyerHub auth

---

nbgrader/docs/source/contributor_guide/releasing.rst
tools/release.py

This also removes running tests when creating the release, but I think these are mostly redundant and take a long time, so I don't think it's worth it to include them.
Closes: #1193

Update releasing instructions

---

nbgrader/nbextensions/assignment_list/assignment_list.js

There was some logic which was causing the fetch assignments to not be refreshed when fetching feedback, which then had the result of not removing the previous items before adding the new items to it. This removes that logic, so that the full assignment list gets refreshed when feedback is fetched, thus ensuring the assignments aren't duplicated.
Ping @dsblank @danielmaitre -- do you remember what the idea behind the original logic was? Is this PR doing the right thing?
Closes: #1188
cc @rkdarst @QuantumEntangledAndy

Do not duplicate assignments when fetching feedback

---

nbgrader/exchange/fetch_feedback.py
nbgrader/exchange/list.py
nbgrader/exchange/release_feedback.py
nbgrader/nbextensions/assignment_list/assignment_list.js
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/tests/apps/test_api.py
nbgrader/tests/apps/test_nbgrader_list.py
nbgrader/tests/apps/test_nbgrader_releasefeedback.py
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/utils.py

This updates the logic for computing the feedback hashes so that the hash depends both on the feedback contents as well as the course, assignment id, notebook id, student id, and timestamp. Feedback files using the previous hashing scheme should still be detected, however, so this should be backwards compatible with previously generated feedback files.
This alleviates the issue in #1141 where it was possible to fetch feedback for only some notebooks in an assignment, which had feedback available because the notebook contents hadn't changed. It also fixes the confusing behavior whereby if a student submits an unchanged assignment, they immediately have feedback available---technically it will be the same behavior, but I found this surprising and confusing since I hadn't gone through the …

Associate feedback files with unique submission attempts

---

dev-requirements.txt

The tests are broken with pytest 4.4 since https://github.com/jupyter/nbgrader/commit/efc57400b04bb8728d9175b3513a1f3497f004b7

Bump pytest required version to 4.5 for custom marker support

---

nbgrader/server_extensions/formgrader/base.py

Formgrader was using the default course id for every call to the Gradebook.
By passing in the course id, every assignment in the gradebook will be created
with the course_id that was set in the config.

Fix formgrader API

---

nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/server_extensions/course_list/handlers.py
nbgrader/server_extensions/validate_assignment/handlers.py

As discovered by @nthiery, the changed internal API in https://github.com/ipython/traitlets
broke the nbgrader build.
This PR implements the change proposed by @minrk, based on the change
to went into ipython here https://github.com/ipython/ipython/pull/10676/files

Move away from using the internal Traitles API to load default configuration.

---

nbgrader/coursedir.py
nbgrader/tests/apps/test_config.py

This enables configuring absolute paths -- and in particular paths
outside of the main course directory for e.g.
c.CourseDirectory.submitted_directory.
Use case: for our course here, we have two separate shared folders (actually git repositories) among instructors. One for the course material, including the source notebooks, which is public. Another for everything involving student submissions, which is private and deleted every year. This PR gives more flexibility in the layout of the two shared folders.

CourseDir.format_path: supports absolute paths in nbgrader_step

---

.coveragerc
nbgrader/nbgraderformat/__init__.py
nbgrader/nbgraderformat/common.py
nbgrader/nbgraderformat/v1.py
nbgrader/nbgraderformat/v2.py
nbgrader/nbgraderformat/v3.py
nbgrader/tests/__init__.py
nbgrader/tests/nbgraderformat/test_v1.py
nbgrader/tests/nbgraderformat/test_v2.py
nbgrader/tests/nbgraderformat/test_v3.py

First PR of several aimed at addressing #1142
This updates the outdated .coveragerc file, and adds a bunch of tests for the nbgraderformat code. I found a few bugs in the process (for example, you couldn't actually use the read and write functions for older versions of the nbgraderformat), so this is clearly a worthwhile exercise 🙂

Improve coverage of nbgraderformat

---

readthedocs-requirements.txt
readthedocs.yaml

readthedocs doesn't know about sphinx_autodoc_typehints, but we don't want to add it into the regular dependencies, so I'm creating a special dependencies file for readthedocs specifically.

Add requirements for readthedocs

---

nbgrader/apps/baseapp.py
nbgrader/exchange/exchange.py

timestamp_format e.g. "%Y-%m-%d-%H-%M-%S-%f" raises an exception ValueError('Unknown string format:', '2019-10-24-20-25-53-460007') in dateutil.parser.parse during collect of submissions. This is due to the dependency of dateutil.parser.parse in parse_utc(). To avoid this during collection of submission, this PR will validate the timestamp_format against dateutils parsing algorithm and raises a TraitError if a ValueError in dateutil.parser.parse occurs.

timestamp_format raises an exception

---

demos/demo_multiple_classes/setup_demo.sh
demos/restart_demo.sh

Demos using Python3

---

nbgrader/converters/base.py
nbgrader/exchange/exchange.py
setup.py

FuzzyWuzzy is GPLv2 licensed which would force you to licence the whole project under GPLv2. I had the same problem on one of my projects and so I wrote [rapidfuzz](https://github.com/rhasspy/rapidfuzz) which is implementing the same algorithm but is based on a version of fuzzywuzzy that was MIT Licensed and is therefor MIT Licensed aswell, so it can be used in here without forcing a License change. As a nice bonus it is fully implemented in C++ and comes with a few Algorithmic improvements making it between 5 and 100 times faster than FuzzyWuzzy. (actually even faster since python-Levenshtein was not used)

use rapidfuzz instead of fuzzywuzzy

---

nbgrader/apps/collectapp.py
nbgrader/exchange/collect.py
nbgrader/tests/apps/test_nbgrader_collect.py

This feature was requested and implemented by one of our users,
@aleksanderilin.
- By default, nbgrader will collect assignments submitted after the
due date (which might get zero points for being late), while there
was something submitted before which would get points.
- This adds a --before-duedate option, which uses the due date in the
gradebook to select.
- Controlled with the "nbgrader collect --before-duedate".  In the
future there could be a "--before=TIMESTAMP" option.
- If there are no assignments submitted before the due date, take the
latest assignment, even after the due date.
- There could be partial credit for things after the due date, so the
it makes sense to take something better after the due date than
worse before.  But, nbgrader can only store one submission and the …

Add nbgrader collect --before-duedate option

---

nbgrader/exchange/fetch_assignment.py

The logic for displaying warning and updating config when a user supplied configuration using the old ExchangeFetch class has a couple of errors in it.
These errors mean that the ExchangeFetchAssignment ignores all configuration passed to it, if there's configurations for the ExchangeFetch class in the config file.
This is especially bad if someone has partially updated an old config file and accidentally left some references to ExchangeFetch in it, while correctly updating other references.
(The ExchangeReleaseAssignment is correct as it is.)

ExchangeFetchAssignment deleting the wrong config

---

nbgrader/docs/source/configuration/jupyterhub_config.rst

- Change [the example in the documentation](https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html) to include `formgrade-` prefix instead of `formgrader-` prefix.

docs: Fix formgrader group name in docs

---

nbgrader/coursedir.py

The CourseDirectory.format_path method behaves differently depending on whether escape is set to True or not. This is because when no escape is needed, the method uses os.path.join, but when escape is set to True, it uses str.join. For most cases this does not matter, but when the path supplied to format_path is absolute, it causes the escaped version to return a different path than the non-escaped one. This is because format_path bases the paths it returns on CourseDirectory.root (it returns join(root, supplied_path_formatted)), and os.path.join will discard all paths before the last absolute path (so os.path.join("/some/path", "/other/path") will return "/other/path"). The str.join version, however, does not work this way.
There're two ways this inconsistency could be solved. Either …

Make format_path behave the same for absolute paths

---

dev-requirements.txt
nbgrader/alembic/versions/167914646830_added_task_cells.py

Gradebook migrations between 0.5.5 and 0.6.1 were failing, due to a mistyped column name in
one of the migrations.

Fix migration, grade cells were looking for a non-existing column

---

nbgrader/alembic/versions/167914646830_added_task_cells.py
nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py

The old code behaviour raises an error in SQLAlchemy 1.3.20 and up.
Fixes #1383

Fix migrations. 

---

nbgrader/tests/utils/test_utils.py
nbgrader/utils.py

This fixes the partial credit bug where the autograder would return full credit when the output was 0. 
closes #1374

partial credit returns zero when score is zero

---

nbgrader/apps/__init__.py
nbgrader/apps/api.py
nbgrader/apps/baseapp.py
nbgrader/apps/generatesolutionapp.py
nbgrader/apps/nbgraderapp.py
nbgrader/converters/__init__.py
nbgrader/converters/generate_solution.py
nbgrader/coursedir.py
nbgrader/docs/source/api/high_level_api.rst
nbgrader/docs/source/command_line_tools/index.rst
nbgrader/docs/source/exchange/exchange_api.rst
nbgrader/tests/apps/test_nbgrader_generate_solution.py

Following issue #1311, I added a few classes for generating the notebooks that contain the solutions to the given assignments. Currently they're available only in the command line interface (I am currently teaching and, unfortunately, I do not have time to get into the details of the Jupyter interface) as an additional subcommand `nbgrader generate_solution <assignment_id>`.
The subcommand creates a solution directory with the notebook containing the solution.
Also I added essential documentation of the new subcommand.

Added CLI for generating solution notebooks

---

nbgrader/preprocessors/execute.py
nbgrader/tests/apps/files/submitted-cheat-attempt-alternative.ipynb
nbgrader/tests/apps/files/submitted-cheat-attempt.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py

If a student disables showtraceback by including:
```python
import IPython.core.interactiveshell
IPython.core.interactiveshell.InteractiveShell.showtraceback = lambda *args, **kwargs : None
```
somewhere in their code, errors won't be recorded in cell outputs, therefore passing and receiving points for those test cases.
If the student provides attempted solutions for each answer that look plausible, this would be hard to notice during manual grading. They could further obfuscate this by representing this exploit as an integer, fetch it from elsewhere using urllib, etc then running it with exec(). The easiest way an instructor could detect this now without having to update nbgrader would probably be to grep all their submissions for "showtraceback" or "exec".

Ensure errors are written to cell outputs to prevent the autograder from awarding points for failed tests

---

nbgrader/tests/test_validator.py
nbgrader/validator.py

Recently I came across multiple kernels (eg. kotlin-jupyter or tslab) that do not create cells of type `error` but rather use stream/stderr to indicate a problem. While this was apparently already fixed for grading
https://github.com/jupyter/nbgrader/blob/7f916faaa6fdad35113c0b80e818ebb87f8cf376/nbgrader/utils.py#L116-L119
it was not considered in the validator. Therefore, this PR changes the validator to be aware of this type of error-reporting.

find cell failure when stderr is used

---

nbgrader/alembic/versions/167914646830_added_task_cells.py
nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
nbgrader/api.py
nbgrader/tests/api/test_models.py
setup.py

Various things seem to have changed in SQLAlchemy, which was causing some test cases to fail as well as many warnings. I have done my best to fix these:
- Ensure enum values are validated
- Remove unnecessary 'aliased' call which was causing errors
- Fix syntax for multiple joins, which was causing errors
- Fix relationships for different types of BaseCells, Grades, and Comments, which was causing warnings
- Use the inspector to get the table names (was causing warnings), and fix this in the alembic migration scripts too
- Use scalar subqueries where appropriate to suppress warnings
This does not fix all of the bugs. There is a strange one that seems to be failing where a submitted notebook doesn't have a student associated with it, and I haven't been able to figure out why. But I am not …

Fix various SQLAlchemy errors and warnings

---

nbgrader/converters/base.py

This allows users to set a custom exporter class in each converter. 
Use case:
We want to enrich student feedback with custom information and need custom filters for this. The easiest way to achieve this is is by using a custom exporter as the _GenerateFeedback_ converter.
Any comments are appreciated.

Make converter exporter class configurable

---

nbgrader/converters/autograde.py
nbgrader/docs/source/user_guide/faq.rst
nbgrader/tests/apps/files/validating-environment-variable.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/validator.py

This also sets the NBGRADER_VALIDATING environment variable during autograding, which notebooks can use to selectively choose to not run certain cells if desired. This also adds a test for this, both for the autograder and for the validator.
Fixes #1415

Use NBGRADER_VALIDATING env var during autograding

---

.github/workflows/test.yml

Use `python -m pip install --upgrade` rather than `pip install -U`, which causes a permission error on Windows.

Fix broken windows tests

---

.github/workflows/test.yml
setup.py

Traitlets v5 (see #1442) no longer supports python 3.6, so we will need to drop support for it as well.

Remove continuous integration for python 3.6

---

nbgrader/converters/base.py

Fixing the problem mentioned in #1376. 
If the hooks are given as an import string (see example) they are now properly imported.
```
nbgrader generate_feedback <assignment-id> --GenerateFeedback.post_convert_hook="my_package.my_hook"
```

Validate pre and post convert hooks

---

dev-requirements.txt
setup.py

Locks setup dependencies to patch versions.

Lock setup dependencies

---

nbgrader/server_extensions/course_list/handlers.py

When using multiple courses multiple instructors the courses tab will crash with an Unauthorized error. This happens when it tries to find local form graders without a token.
The fix is to just add `ConnectionRefusedError` exception handler. In which case it will gracefully continue to looking for Jupyter hub formgraders instead of erroring out.
Fixes: #1292

Fix Issue with Courses tab on Multi courses

---

nbgrader/docs/source/user_guide/managing_assignment_files.ipynb
nbgrader/docs/source/user_guide/managing_assignment_files_manually.ipynb

- Rename to "Exchanging assignment files" - the previous name could
mean almost anything related to nbgrader, and uses the standard
terminology.
- Adjust the introduction sections so that each page describes the
reason you would read it.  For the 'manual' page, there are more
rearrangements here, since the focus has changed a lot.  But nothing
is completely lost (though maybe it should be, to reduce redundancy)
- There is more to do to improve, but I am trying to start small and
get some basic stuff done.
- Review: General check, but not too much, we should keep iterating.

docs: revise "Managing assignment files" pages

---

nbgrader/docs/source/index.rst

- Rename the "Configuration" section to "Setup and Configuration" -
this section is focused on the ones administrating a nbgrader
install for others (or themselves).
- Move the "Installation" and "What is nbgrader?" pages to this new
section.
- The motivation is to keep the "User guide" focused on people using
nbgrader, something we might send to a instructor or student who
needs to get started.  The next section starts on things that
administrators might need to know.  Unlike a lot of software, we
expect a bigger difference between users and admins here, at least
for hub-based setups.
- I have not moved the pages, so they are still in the `user_guide/`
section, not `configuration/`.  While not idea, I consider this less
bad than moving - for now.  They can be rearranged later.
- Review: …

docs/index: Move setup-related topics to configuration section

---

nbgrader/docs/source/user_guide/highlights.rst

Rearrange the highlights page into three sections, and introduce a section giving a minimal example of the notebook format.  This introduces some of the changes discussed in #1491.  I recommend looking at the commits separately, to easily understand what is going on and see more about each change.
To review: general text and all, also the general clarity and message of the change.

docs: update highlights to introduce the notebook format

---

nbgrader/docs/source/contributor_guide/database.rst
nbgrader/docs/source/contributor_guide/documentation.rst
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/what_is_nbgrader.rst

Sphinx linkcheck reported one broken link, which caused docs CI to
fail.  This fixes the one broken link, and updates several other
redirects to https.  Other ones *could* be updated but seem reasonable
to leave as well.
Review: general check and merge (other CI is broken, too).  Check if
the docs build group passes, I'm curious if other things are broken.

Improve CI by running sphinx linkcheck

---

.github/workflows/test.yml

Add Python 3.10 to our testing workflows.

Add Python 3.10 to CI pipeline

---

.github/workflows/enforce-label.yml

Similar to the workflows used in other Jupyter projects:
- https://github.com/jupyterlab/jupyterlab/blob/master/.github/workflows/enforce-label.yml
- https://github.com/jupyter-server/jupyter_server/blob/main/.github/workflows/enforce-label.yml
This will be useful when adopting the Jupyter Releaser (#1570), so each PR has a label and the changelog be nicely generated.

Add workflow to enforce GitHub labels

---

nbgrader/tests/nbextensions/test_create_assignment.py

This PR fix a false positive in `test_create_assignment`.
Sometime the `blank` notebook was loaded instead of the `task` notebook, which made the test pass.

Fix a false positive test

---

nbgrader/converters/autograde.py

When groupshared is enabled (`c.CourseDirectory.groupshared = True`), the default permission in `BaseConverter` class will be changed to `664`, which is expected. However, since `autograde.py` is also inherited from `BaseConverter` class in `convertes/base.py`, this will make permission of autograded notebooks to be `664` as well, which is not wanted, because those files should be read-only (444) to grader as it's when `groupshared = False`.
This PR will set the default permission of `Autograde` class to `444`, regardless of whether the groupshared is True or False.

[converters/autograde] Fix autograded notebook permission

---

nbgrader/converters/generate_feedback.py

In nbgrader v0.6.x we only set the `template_path` option if it is not already in the config (see [here](https://github.com/jupyter/nbgrader/blob/0.6.x/nbgrader/converters/generate_feedback.py#L60)). 
In nbgrader v0.7.x we should also only set the the `extra_template_basedirs` conditionally in order to not break any custom exporters.

Only add extra_template_basedirs if it has not been set

---

etc/jupyter/jupyter_notebook_config.json
etc/jupyter/jupyter_server_config.d/nbgrader.json
nbgrader/__init__.py
nbgrader/exchange/abc/exchange.py
nbgrader/server_extensions/assignment_list/__init__.py
nbgrader/server_extensions/assignment_list/handlers.py
nbgrader/server_extensions/course_list/__init__.py
nbgrader/server_extensions/course_list/handlers.py
nbgrader/server_extensions/formgrader/__init__.py
nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/formgrader.py
nbgrader/server_extensions/validate_assignment/__init__.py
nbgrader/server_extensions/validate_assignment/handlers.py
pyproject.toml
setup.py

This PR is a starting point for using labextensions :
- Switch from IpythonHandler from notebook to JupyterHandler from jupyter_server
- Enable jupyter-server and classic notebook server extensions during installation (fix #1465)

Jupyter server

---

setup.py

The newer version of traitlets is causing the tests to fail, as it does not seem to be using the right log level.

Pin traitlets dependency for 0.7.x

---

nbgrader/server_extensions/formgrader/handlers.py
nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2

This PR fix an error when loading MathJax in formgrade template.
*HTMLExporter* in `nbconvert>6` replace the variable `resources['mathjax_url']` with https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe.
That was breaking the loading of *MathJax* in formgrade template.

Fix mathjax in formgrade templates

---

demos/restart_demo.sh
nbgrader/docs/source/user_guide/advanced.rst
nbgrader/docs/source/user_guide/what_is_nbgrader.rst
nbgrader/exchange/default/exchange.py

The default exchange directory cannot be created on mac (#1589). This changes the default directory to a location that can be created on both mac and linux. While the exchange is technically not really supported on mac, this makes it less of a headache to test stuff out on mac (because it removes the need to edit config files).
I would appreciate some feedback on this before merging, in case it might cause problems for folks I'm not aware of? @rkdarst @BertR @perllaghu

Change default exchange path

---

style/assignment_list.css
style/common.css
style/course_list.css
style/create_assignment.css
style/validation_message.css

Change the hard coded CSS color by Jupyterlab CSS variables in labextension to allow changing theme (light and dark).
Only the formgrader extension remains in light style as it depends on bootstrap.

Use jupyter css variable in labextension to manage colors with theme

---

.github/workflows/test-labextensions.yml
src/create_assignment/create_assignment_extension.ts
src/create_assignment/index.ts

This PR improves the behavior of the `create assignment` widget :
- If no Notebook is visible in main area, clicking on the button does not open the right panel (instead of opening an empty one)
- if a notebook is visible, it will be activated (can occur when the main area is split)
- if the selected tab in main area becomes a tab which is not a Notebook, the `create assignment` panel is closed

Create assignment panel only open if a Notebook is visible on main area

---

setup.cfg

Pins selenium version to `4.2` as the latest `4.3.0` breaks tests.

Pins selenium version to 4.2

---

.github/workflows/check-release.yml
demos/restart_demo.sh
nbgrader/_version.py
nbgrader/docs/source/contributor_guide/installation_developer.rst
nbgrader/nbextensions/assignment_list/main.js
nbgrader/nbextensions/course_list/main.js
nbgrader/nbextensions/validate_assignment/main.js
pyproject.toml
setup.cfg
src/assignment_list/index.ts
src/course_list/index.ts
src/validate_assignment/index.ts
tools/post-bump.py

Running the Draft Changelog on the `main` branch failed with the following error:
```
Error: Could not parse 0.8.0a0 as a valid version string
```
https://github.com/jtpio/jupyter_releaser/runs/7023597896?check_suite_focus=true
This looks related to bumping the version for pre-releases.
This change should fix it.

Fix version bumping for pre-releases

---

tools/post-bump.py

Follow-up to https://github.com/jupyter/nbgrader/pull/1610
As noticed in https://github.com/jupyter/nbgrader/pull/1613 the JS version is missing a `.`.

Fix missing `.` in the JS version

---

CHANGELOG.md

Automated Changelog Entry for 0.8.0a0 on main
```
Python version: 0.8.0a0
npm version: nbgrader: 0.8.0-alpha.0
```
| Version Spec | 0.8.0a0 |
| Since Last Stable | true |

Automated Changelog Entry for 0.8.0a0 on main

---

package.json
pyproject.toml

Brings together all `jupyter_releaser` hooks  in `pyproject.toml` file,  it seems that the jupyter_releaser do not run the hooks from 2 sources.
cc @jtpio for review

Move the jupyter_releaser hooks from package.json to pyproject.toml

---

CHANGELOG.md

Automated Changelog Entry for 0.8.0a1 on main
```
Python version: 0.8.0a1
npm version: nbgrader: 0.8.0-alpha.1
```
| Version Spec | next |
| Since | v0.8.0a0 |

Automated Changelog Entry for 0.8.0a1 on main

---

setup.cfg

The latest `nbclassic` version `0.4.0` breaks nbgrader so for now it should be pinned in a previous version.

Pin version of nbclassic<0.4.0

---

CHANGELOG.md

Automated Changelog Entry for 0.8.0a2 on main
```
Python version: 0.8.0a2
npm version: nbgrader: 0.8.0-alpha.2
```
| Version Spec | 0.8.0a2 |
| Since | v0.8.0a1 |

Automated Changelog Entry for 0.8.0a2 on main

---

nbgrader/server_extensions/assignment_list/handlers.py

This PR remove a dependency to `notebook.utils` available in `jupyter_server`.

Remove a remaining dependency to notebook

---

.github/workflows/binder.yaml

This PR adds a GITHUB-TOKEN to binder workflow, as required

Add required github-token in workflow

---

CHANGELOG.md

Automated Changelog Entry for 0.8.0 on main
| Version Spec | 0.8.0 |
| Since Last Stable | true |

Automated Changelog Entry for 0.8.0 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.8.1 on main
| Version Spec | next |
| Since | v0.8.0 |

Automated Changelog Entry for 0.8.1 on main

---

nbgrader/tests/nbextensions/formgrade_utils.py
nbgrader/tests/nbextensions/test_assignment_list.py
nbgrader/tests/nbextensions/test_course_list.py
nbgrader/tests/nbextensions/test_create_assignment.py
nbgrader/tests/nbextensions/test_formgrader.py
nbgrader/tests/nbextensions/test_validate_assignment.py

EDIT : Fix https://github.com/jupyter/nbgrader/issues/1612
All the methods like `find_element_by_*` and `find_elements_by_*` have been removed from selenium 4.3.0.
This PR replaces them by `find_element(By.*, ...)` and `find_elements(By.*, ...)`.

Fixes selenium tests

---

nbgrader/apps/baseapp.py

This PR is to (re)allow loading configuration file from current working directory.
This feature has been removed from [jupyter_core](https://github.com/jupyter/jupyter_core/commit/1fd79f9c192d4c56235ec1847f18d3b079b722b9) for security reasons (https://github.com/advisories/GHSA-pq7m-3gw7-gq5x).
This will fix the tests on extensions which are broken since the last release of jupyter_core.
For what I understand it should only load configuration file for nbgrader, it should not reintroduce the security error.

Allow current working directory for nbgrader config file only

---

demos/Dockerfile
demos/restart_demo.sh

This PR fix #1668.
- It installs `nodejs=16` (not available on apt) in docker image
- it pins `nbclassic<0.4.0` as currently expected by nbgrader. 
If nbclassic is not pinned, the v0.4.0 is first installed with jupyterlab. When installing nbgrader, the `v0.4.0` is uninstall in favor of `v0.3.7`. It seems that it breaks `jupyter-nbextension`...

Fix Docker image for demo

---

pyproject.toml

Pins `jupyter_server<2` because it breaks `nbextension` tests.
It must be unpinned as soon as the classic notebook is no longer maintained.

Pin jupyter_server<2

---

nbgrader/docs/source/configuration/jupyterhub_config.rst
yarn.lock

This pr fixes a broken link in the docs and updates `node-canvas` so that a binary is actually available.
A testing error caused by JupyterLab Announcement extension remains unfixed because I don't know what is the best way to disable that (isolated to the testing process).

Fixes for testing CI

---

README.md

This PR removes the broken `codecov` badge in the `README.md` file.
I think some right (that I don't have) are necessary to fix it.
I'll open an issue to restore it.
cc. @jhamrick

Remove codecov badge

---

nbgrader/docs/source/configuration/nbgrader_config.rst

I recently ran into a problem when using `nbgrader quickstart`. In the docs currently, one example given [here](https://nbgrader.readthedocs.io/en/stable/configuration/nbgrader_config.html#use-case-1-nbgrader-and-jupyter-notebook-run-in-the-same-directory) is
```
nbgrader quickstart ./course101
```
which results in a `nbgrader_config.py` with `course_id = "./course101"`. However, in other parts of the code, the course id seems to be determined via reading directories, so is set to `"course101"`.  This then causes problems in at least in feedback related functions when `notebook_hash` is called, leading to different hashes for the same assignment.
I don't know what is the best way to fix this, maybe adding a check somewhere that limits/sanitizes course ids would work. 
This pull request …

Changed quickstart example

---

nbgrader/tests/labextension_ui-tests/tests/test_assignment_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_course_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_create_assignement.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_validate_assignment.spec.ts

This PR suppresses notifications during UI testing, to prevent some tests from failing because of them.
Fix the first item of https://github.com/jupyter/nbgrader/issues/1736

Remove the notification during UI tests, to fix a failing test

---

nbgrader/tests/apps/files/validation-zero-points.ipynb
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/utils.py
nbgrader/validator.py

If a cell gets full points during validation, check if max_points is 0 and the cell actually failed. Fixes (part of) #1418.
If this looks good, I can also add some related tests.

Fix validation for failed cells with zero points

---

.github/workflows/test-docs-python-nbextensions.yml
.github/workflows/test-labextensions.yml

Python 3.7 is not supported anymore by `ipython`, which breaks the dependencies installation for tests.
This issue occurs when upgrading `ipython`, see https://github.com/jupyter/nbgrader/pull/1690#issuecomment-1462592055
This PR drops Python 3.7 in tests, and includes Python 3.11.
It also upgrades the Linux distribution used in tests, from Ubuntu 20.04 to Ubuntu 22.04.

Upgrade python requirement

---

pyproject.toml

The requirement of a specific traitlets version was first set in commit 35ed7aae9a72a4a7f2e4d9117eb8f0ae6bac6411 to be <5.2 because apparently 5.2 broke tests.
The last time this line was updated was in #1704, where it was bumped up to allow the latest version at the time, 5.6, by setting the value to <5.7. There was an additional change in #1704 which sets a log level, but this seems to be backwards compatible.
These changes seem to no longer be relevant as the test suite now passes with traitlets versions 5.2, 5.7, as well as many others >5. The only version I found to fail was 5.0.0.
This commit loosens the version requirement to allow these other versions of the traitlets package which don't cause known conflicts, as well as allow future minor, but not major version bumps.

Loosen the traitlets version requirement

---

nbgrader/exchange/default/list.py
nbgrader/server_extensions/assignment_list/handlers.py

The `view feedback` link does not work when the `root_dir` of JupyterLab is different from './'.
The reason is that the feedback path is not relative to the `root_dir` but to the directory where nbgrader started.
This PR solves the problem by changing the feedback path to a relative path from `root_dir`.
I observed the same issue with classic notebook (in version `0.7.x`) if the `notebook_path` is different from './'.
This PR should probably be back ported to `0.7.x` branch.
Close https://github.com/jupyter/nbgrader/issues/1664

Fix view feedback link when root_dir is set

---

pyproject.toml

`MarkupSafe` has been primarily added when jinja2 has been pinned to version `<3` (https://github.com/jupyter/nbgrader/pull/1559).
Currently it is `jinja2>=3`, the dependency on MarkupSafe can probably be removed.

Removes dependency to MarkupSafe<2.2.0

---

demos/restart_demo.sh
pyproject.toml

`nbclassic` has been pinned to version `<0.4.0` because of *Mathjax* issue (https://github.com/jupyter/nbgrader/issues/1622).
The current version is `<0.5.0` and it seems there is no *Mathjax* issue anymore.
There is no need to pin it anymore.

Unpin nbclassic

---

nbgrader/coursedir.py
nbgrader/exchange/default/exchange.py
nbgrader/tests/apps/test_nbgrader_submit.py

The previous maximum size option was applied to individual files only. This adds a separate option to limit the maximum size of the entire directory. The option is called max_dir_size and is implemented similarly to max_file_size. The default is same as the max file size.

Add maximum size for entire directory as submission option

---

src/assignment_list/assignmentlist.ts
src/assignment_list/index.ts
src/course_list/index.ts
src/formgrader/index.ts

Fixes #1722 and changes "fetch" to "Fetch" in lab assignment-list, to be more consistent with the rest of the buttons.

Fix blank tab names and labextension button label

---

nbgrader/tests/labextension_ui-tests/tests/test_assignment_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_course_list.spec.ts
nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
src/assignment_list/index.ts
src/course_list/index.ts
src/formgrader/index.ts

Fixes  #1772
I did not add tests to reproduce the issue. This would require a bit more work.

Recreate nbgrader widgets after they are disposed.

---

nbgrader/preprocessors/execute.py
nbgrader/tests/apps/files/timeout.ipynb
nbgrader/tests/apps/test_nbgrader_autograde.py
nbgrader/tests/apps/test_nbgrader_validate.py
nbgrader/validator.py

<s>Make timeout configuration work via:
- either `c.Execute.timeout` or `c.ExecutePreprocessor.timeout` in `nbgrader_config.py` or,
- `--Execute.timeout` or `--ExecutePreprocessor.timeout` in the command-line.</s>
- 
Since  #1690 is now merged, this pr also makes `error_on_timeout` configurable and makes it actually printed on command line or included in Notebook/Lab response messages.
In the case of validating, the current implementation does not use configuration in the way `traitlets` expects, in that it just calls `preprocessor({"timeout": x})`, which is caught by `ExecutePreprocessor` (this may work, but only by accident). By giving the argument `parent=self`, the configuration is deferred to the initialization of `Configurable`, which knows how to do it properly.

Timeout configuration in validation and error message

---

nbgrader/server_extensions/formgrader/static/js/gradebook_notebook_submissions.js
nbgrader/server_extensions/formgrader/templates/gradebook_notebook_submissions.tpl
nbgrader/tests/labextension_ui-tests/tests/test_formgrader.spec.ts
nbgrader/tests/nbextensions/test_formgrader.py

Adds a new button in gradebook_notebook_submissions view to toggle visibility of all student names, closes #951.

Toggle visibility of all student names

---

pyproject.toml

Pins `sphinx<7` in *docs* dependencies, `sphinx-rtd-theme` is not compatible with it yet:
https://github.com/readthedocs/readthedocs.org/issues/10279

Pin sphinx<7

---

nbgrader/preprocessors/clearmarkingscheme.py
nbgrader/tests/preprocessors/test_clearmarkscheme.py

Fixes https://github.com/jupyter/nbgrader/issues/1782. ~The problem of adding images to marking schemes remains unsolved.~

Check marking schemes for attachments to prevent leakage

---

nbgrader/alembic/versions/167914646830_added_task_cells.py
nbgrader/alembic/versions/e43177bfe90b_added_course_table_and_relationships.py
nbgrader/api.py
pyproject.toml

Most of the required changes so far were fairly innocent.
One of the warnings when running on `sqlalchemy<2` was [this one](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#change-5150) about changing cascade_backref behavior. It is still a bit unclear to me what consequences this change might have, but tests were passing on `sqlalchemy<2` with using `future=True` in `Session` and `Engine`, and they are passing now.

Upgrade to sqlalchemy>=2

---

nbgrader/preprocessors/overwritecells.py
nbgrader/tests/preprocessors/test_overwritecells.py

Add a new flag `OverwriteCells.add_missing_cells`, that, when set to `True`, compares the submitted notebook to the database before autograding and adds missing grade cells to (approximately) correct locations.
Fixes https://github.com/jupyter/nbgrader/issues/1682 (with the provided flag).
- Missing grade cells are added immediately after the previous grade/solution cell, because presumably the notebook structure is repeated blocks of
```
question students should answer (solution cell)
test for the above (grade cell)
test for the above (grade cell)
...
```
- The above doesn't apply to manually graded answers, and currently I can't think of a good way to find their correct location based on the database
- Missing cells could be added based on the notebook in the `released/` directory, but …

Add missing grade_cells before autograding

---

nbgrader/api.py

This PR is only a rebase of https://github.com/jupyter/nbgrader/pull/1799 opened by @tuncbkose.

Revert change breaking sqlalchemy 1.4.x

---

.github/workflows/test-extensions.yml
package.json
yarn.lock

This PR fixes a compatibility error in node packages, and adds a test on it.
Fixes https://github.com/jupyter/nbgrader/issues/1826

Labextension compatibility

---

pyproject.toml

Fix https://github.com/jupyter/nbgrader/issues/1838
This PR adds a dependency to *setuptools*.
*setuptools* should normally be installed as a dependency of *babel*, itself a dependency of *jupyterlab_server*.
Nevertheless, it seems that some version of babel do not have this explicit dependency (e.g. `babel==2.10`), which can lead to instable installation of *nbgrader*.

Add a dependency to setuptools

---

nbgrader/server_extensions/course_list/handlers.py
src/course_list/courselist.ts
src/index.ts

This PR fixes https://github.com/jupyter/nbgrader/issues/1829
It also adds a new option to open the *formgrader* panel from the URL search param (`formgrader=true`).
Which is useful when opening a new nbgrader service with jupyterhub, to redirect automatically to the formgrader panel

Fix formgrader link from course_list

---

nbgrader/nbgraderformat/v1.py
nbgrader/nbgraderformat/v2.py
nbgrader/nbgraderformat/v3.py

The typing.io namespace was deprecated in python 3.8, which is the lowest version currently supported by nbgrader.
https://docs.python.org/3/library/typing.html#aliases-to-other-concrete-types

Remove use of deprecated typing.io

---

package.json
yarn.lock

This PR add `@jupyter` namespace to the NPM package, to move the package in the jupyter org.
Context at https://github.com/jupyter/nbgrader/pull/1874#issuecomment-2025467640.

Transfer the NPM package to @jupyter namespace

---

pyproject.toml
src/index.ts

Follow up https://github.com/jupyter/nbgrader/pull/1875 to change the plugin IDs and to install the labextension in the correct directory (`'@jupyter/nbgrader`).
This change is required to use the schema files (settings), i.e. https://github.com/jupyter/nbgrader/pull/1859

Install the labextension in the correct directory 

---

nbgrader/apps/baseapp.py
nbgrader/docs/source/build_docs.py
nbgrader/docs/source/configuration/nbgrader_config.rst
nbgrader/server_extensions/formgrader/base.py
nbgrader/server_extensions/formgrader/formgrader.py
nbgrader/server_extensions/formgrader/handlers.py
nbgrader/server_extensions/formgrader/templates/manage_assignments.tpl
nbgrader/tests/ui-tests/formgrader.spec.ts
package.json
schema/formgrader.json
src/index.ts
yarn.lock

This PR aims to open formgrader with a configuration file (*nbgrader_config.py*) from the local directory.
Currently, the formgrader loads the *nbgrader_config.py* files from:
- the directories in `jupyter_config_path`
- the directory where Jupyter lab started: `os.cwd()`
- the directory `CourseDirectory.root` (which can be configured by one of the previous files)
With this PR, it will be possible to start the Formgrader with a config file in the curent directory in lab filebrowser, by using the new menu entry *Formgrader (local)*.
It will reinitialize the `FormgradeExtension` object with the additional configuration of the current directory.
In this case, the configuration file existing in the root directory of Jupyter lab app will not been loaded.
Using the classic menu entry …

Open formgrader with a local configuration file

---

nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/autograded/bitdiddle/ps1/problem2.ipynb
nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/autograded/hacker/ps1/problem2.ipynb
nbgrader/docs/source/user_guide/downloaded/ps1/archive/ps1_hacker_attempt_2016-01-30-20-30-10_problem1.ipynb
nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem1.html
nbgrader/docs/source/user_guide/feedback/bitdiddle/ps1/problem2.html
nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem1.html
nbgrader/docs/source/user_guide/feedback/hacker/ps1/problem2.html
nbgrader/docs/source/user_guide/release/ps1/problem1.ipynb
nbgrader/docs/source/user_guide/release/ps1/problem2.ipynb
nbgrader/docs/source/user_guide/source/header.ipynb

The current notebooks are incorrectly rendered because the dollar sign should not be perceded by a space to be rendered correctly in Visual Studio Code cells, adding a space around them fixes the problem, however it does render correctly on GitHub.
The part in red is the default format, the part in green is the fixed format.

Fixed LaTeX rendering in some demo notebooks

---

nbgrader/converters/autograde.py
nbgrader/preprocessors/__init__.py
nbgrader/preprocessors/ignorepattern.py
nbgrader/tests/preprocessors/files/warning-pattern.ipynb
nbgrader/tests/preprocessors/test_ignorepattern.py

Creating a new preprocessor, which is useful for removing specific warning cells that might result in a false-negative autograde result. This is used when the assignment is already out and released, but you notice a problem in a test after the fact. This provides a much easier way of recovering compared to editing the assignment.
We at @aaltoscicomp came across an issue where Torch raised a specific warning on stderr (due to some avx1 incompatibility in the node on which the grading would happen), and the auto-grader would mark the solution as wrong. Since the warning was not a Python Warning object (NNPACK.cpp warning), it cannot be suppressed the usual way. Since this warning can't be easily predicted in advance, the assignment couldn't be made to compensate for it.
We addressed the …

New Autograde Preprocessor: IgnorePattern

---

.github/workflows/check-release.yml
.github/workflows/test-extensions.yml

The v2 of upload artifact action is now deprecated and must be upgraded.
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Upgrade upload-artifact action

---

nbgrader/exchange/default/release_feedback.py

Groupshared users could not re-release student feedback due to shutil.copy functionality used by release_feedback. Shutil.copy tries to chmod the destination file which does not work in groupshared scenarios where files have different owners but same groups. Therefore groupshared users cannot copy a new generated feedback with the same name over the old one owned by another user. In the fix the file gets copied in a temporary location and is moved over the old file. 
Tests were not implemented as I believe it is not possible to test interactions requiring multiple users automatically. To replicate the issue, you need two users with groupshared enabled that release feedback for the same student's assignment.

groupshared feedback re-release fix

---

package.json

This PR should prevent dependabot from using yarn 4, and change the whole dependencies in `yarn.lock`.
See https://github.com/jupyterlab/extension-template/pull/79 for more information.

Prevent dependabot from using yarn 4

---

nbgrader/server_extensions/formgrader/base.py

This PR solves issue #1870 (formgrader does not show in JupyerLab tab due to JupyterHub >=4.1.0 security settings in HTTP headers).
Starting with JupyterHub 4.1.0 HTTP header
```
Content-Security-Policy:  frame-ancestors 'none'
```
is the default setting instead of
```
Content-Security-Policy: frame-ancestors 'self'
```
See [Mitigating same-origin deployments](https://jupyterhub.readthedocs.io/en/stable/explanation/websecurity.html#mitigating-same-origin-deployments) for some background on this decision and [CSP: frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#self) for details on the header.
The `none` header prevents loading of formgrader in a tab of JupyterLab.
The JupyterHub `none` setting overwrites the `self` setting …

Set CSP frame-ancestors 'self' for nbgrader handlers

---

.github/workflows/check-release.yml

This PR update the `check_links` to use the one from [maintainer_tools](https://github.com/jupyterlab/maintainer-tools/blob/main/.github/actions/check-links/action.yml) instead of the old one from [jupyter_releaser](https://github.com/jupyter-server/jupyter_releaser/blob/1.x/.github/actions/check-links/action.yml).
It also ignore the [MIT link](https://github.com/jupyter/nbgrader/blob/8563de4fae20d43b1035b967a3431b1d2d4eeaf1/nbgrader/server_extensions/formgrader/static/components/autosize/readme.md?plain=1#L39) from a javascript dependency, which constantly fails.

Update the check link action to use maintainer tools

---

package.json
yarn.lock

The current version of `npm-run-all` block updating `cross-spawn`.
This leads to a security issue https://github.com/jupyter/nbgrader/security/dependabot/52.
looks like this package is not necessary, this PR removes it.

Replace npm-run-all by npm-run-all2

---

nbgrader/tests/ui-tests/assignment_list.spec.ts
nbgrader/tests/ui-tests/course_list.spec.ts
nbgrader/tests/ui-tests/formgrader.spec.ts

Previously, UI tests failed on macOS because the required keyboard shortcuts are slightly different on macOS from Windows and Linux. This commit updates them to use the ControlOrMeta key, which handles both cases.

fix: Use cross-platform shortcuts in ui-tests

---

nbgrader/preprocessors/overwritekernelspec.py
nbgrader/tests/preprocessors/test_overwritekernelspec.py

The `Notebook.kernelspec` field is nullable, so in the event of a null value, OverwriteKernelspec should not fail. This commit checks for that case before trying to `json.loads` the value.

fix: Allow null kernelspec in OverwriteKernelspec

---

nbgrader/api.py

Most notably, Grade.cell_type was defined as an association_proxy in the class, but was later overwritten with a column_property. Because the mapper had already been made aware of the association_proxy, this raised a warning. Grade.max_score also had a similar problem, with a column_property overwriting a regular @​property.
This commit fixes the warnings by replacing the in-class field definitions with `field = None`.
Additionally, remove duplicate definitions for `cell_type_gradecell` and `cell_type_taskcell`.
Fixes #1946

Resolve warnings in SQLAlchemy field defs
